### ISSUE TITLE
Add content from CHRIJ to the landing pages

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#104]
Due November 17, check in meeting Nov 7 re progress. Heads up @ggeisler @marlo-longley that this is in progress. 

Here is the doc they are working in, includes Series descriptions:
https://docs.google.com/document/d/1uINHypHUMq5ku_4IYrm_BHQL9vQaREzemtHm48OmSHk/edit#heading=h.4hjd4v3ce37g

Need to also create information about the limitations of the data at this stage, specifically for browsing dates and language - not every record is dated, many dates are missing. Try to be explicit about what user can expect.

**Comment by marlo-longley** [comment]
Blocked waiting on content from CHRIJ

**Comment by laurensorensen** [comment]
CHRIJ updated to say they will have this after Thanksgiving break

**Comment by laurensorensen** [comment]
I got Penelope's ok to go ahead for the text - we can pair whenever is convenient to input the text @marlo-longley

**Comment by marlo-longley** [comment]
Here is the link to the finalized content: https://docs.google.com/document/d/1ZbUTyMJ--mHVliU8uScroL2N-oGdvTexNOBoUA8i7lc/edit#

Categories of text to add to the app are:
- [ ] VT landing page text
- [ ] NTA landing page text
- [ ] Staff to Acknowledge
