### ISSUE TITLE
Add Feedback link and functional form

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#129]
Mentioned in #66. We need to:

- [ ] Add a Feedback link to the topbar 
- [ ] Display a feedback form when triggered by that link
- [ ] Send the completed form to the appropriate recipients

Although we haven't been 100% successful, we have in recent years tried to make the Feedback link and associated form consistent among SUL applications (at least the applications managed by the Access team). This enables users of multiple SUL applications to learn our pattern for providing feedback and know where to find the link, etc.

So when developing the solution here I suggest using one of the existing implementations as a model. Exhibits might be a good one to use (e.g., Searchworks adds some additional elements not applicable here). The visual look and function of the NTA feedback link and form should be just like the existing implementations (clicking the Feedback link toggles open and close the form, etc.).

<img width="1089" alt="Screen Shot 2022-11-01 at 10 55 21 AM" src="https://user-images.githubusercontent.com/101482/199305894-a480fcf1-a022-4c6b-831f-b6376a29708c.png">

---

**A: Add a Feedback link to the topbar**

**B: Display a feedback form when triggered by that link** - @laurensorensen In theory we could add more fields here, but I don't think we should unless you can think of a good reason to. I just mention it in case you do have any ideas for additional form fields you think would be critical for NTA users to be able to fill out and submit. But if possible we should keep it as-is (simple and appropriate for a wide range of types of feedback).

The "Reporting from" alert box is red in Exhibits, but I'd prefer it be `alert alert-info` blue (as in my mockup above), so that might be the one change if using the Exhibits version as a model (for whatever reason, we used `alert alert-primary` there and get a red box).

**C: Send the completed form to the appropriate recipients** - @laurensorensen I think it is your call on who should receive NTA feedback form submissions. Sometimes this goes to a list, but it could also go to one or more individual email addresses (e.g., just you;  you, Hannah, and Penelope; you and an ICJ group address, etc.). Exhibits feedback submissions also go to a JIRA project, but I'm not sure that's appropriate here (Hannah and/or Cathy might have thoughts/suggestions on the recipients issue.)

**Comment by cbeer** [comment]
We should also make sure to add recaptcha (like we do in other apps) to keep bot spam down.

**Comment by jcoyne** [comment]
Blocked by https://github.com/projectblacklight/blacklight/pull/2866

**Comment by jcoyne** [comment]
Now blocked by https://github.com/projectblacklight/arclight/pull/1310

**Comment by jcoyne** [comment]
@laurensorensen can you tell me who should get this mail?

**Comment by laurensorensen** [comment]
> 

@jcoyne the form should go to: virtualtribunals-contact@lists.stanford.edu

**Comment by marlo-longley** [comment]
Closed by #213

**Comment by ggeisler** [comment]
I'm reopening this because the current implementation doesn't match the intended design in several significant ways. I'm not being nitpicky here; as I noted in the original description of this ticket, we've intentionally made an effort to update the Feedback form in the various Access team applications to be more consistent (they aren't completely in alignment yet, but more so than in the past) so that our users will see a familiar pattern for providing feedback across our applications, which makes the forms more approachable and thus better encourage user feedback.

For reference, here's an Exhibits (Purl, Searchworks, MyAccount, etc are similar) feedback form:

<img width="955" alt="Screen Shot 2023-01-09 at 1 41 15 PM" src="https://user-images.githubusercontent.com/101482/211421019-65661731-71a8-4b65-be0b-1ab446db2b8e.png">


And here's the current VT feedback form:

<img width="955" alt="Screen Shot 2023-01-09 at 1 38 19 PM" src="https://user-images.githubusercontent.com/101482/211421044-c85e1adb-a52e-4961-9b92-c1f6784bcb8d.png">


These are the things I think we should fix so the VT feedback form more closely resembles our other forms and provides a better user experience to VT users:

**A: Expose the "Reporting from" URL** - One thing we've improved with the feedback form in all of our applications is displaying an alert box with the current URL. Displaying this prominently tells the user we know what page their feedback might relate to, and reduces the amount of clutter we used to get in the feedback responses where the user tries to describe (often not with the URL and ambiguously) what page they are on. Also, if the URL is not currently passed on as part of the form submission, it should be, since we want to know where the user was when submitting the form, and by showing the alert box we're suggesting that the user not include that in their message.

**B: Right-align and increase the font-weight of the field labels** - Use `font-weight: 600` for the field labels to make them a bit stronger. Right-align the labels at viewport widths of `768px` and above. (Some of our apps leave them right-aligned at all viewport widths, but I think that is an oversight).

**C: Decrease the width of the form inputs** - It looks like the HTML/Bootstrap classes used for the form structure is different in VT than our other applications. As a result, the form fields are wider than in our other applications at the same viewport width. The narrower width in our other applications is intentional because wide form input fields make for long line lengths and poorer UX for the user filling out the form. Also, although it's not really my business to dictate code structure, it does seem like using the same structure as in our other applications would make long-term maintenance easier (i.e., if we want to add or change something in the form, it's the same steps to update in all feedback form instances).

**D: Increase the height of the Message textarea** - In our other applications we use either 4 or 5 rows for the textarea, which gives the user writing a medium-length or longer message a better chance of seeing it all (without scrolling) as they type. A taller message area also encourages the user to write more than a cursory message. Mostly our other feedback form textareas are 5 rows, so I suggest that for the VT form, which is currently only 2 rows.

**E: Change the 'Reset' label** - "Reset" might make sense to a developer, but to users the label "Cancel" is much more familiar and descriptive ("Reset" doesn't imply to a non-technical user that the form will close if they select that action, just that any form entries might be cleared). We use "Cancel" as the label in all other feedback forms so we should do the same here.

**E: Change the 'Reset' behavior** - In all of our other feedback forms, selecting "Cancel" simply closes the form; any form field entries are **not** cleared. In the current VT form, selecting "Reset" both closes the form and clears any field entries. I believe the behavior in our other applications is what we also want in VT. The rationale is that because opening the feedback form consumes vertical height in the viewport, the user might have lost sight of something further down the page that they need to reference when filling out the form. So we should leave any form entries alone when they select "Cancel" so they are still visible if the user opens the form again before they've left the page (we don't need try to preserve any form field entries if the user navigates away from the current page).

**Comment by jcoyne** [comment]
@ggeisler do these differences in C stem from differences in breakpoints between Bootstrap 4 and 5? 

Regarding font weight, library hours does not use a bold text on it's feedback form.  Should that be fixed? 

E if we want it to close, should we consider labeling it "Close" instead of "Cancel"?  "Cancel" to me means, I don't want to proceed with whatever I was doing and I'd expect it to clear out.

**Comment by ggeisler** [comment]
@jcoyne 

> do these differences in C stem from differences in breakpoints between Bootstrap 4 and 5?

I don't believe so. Our other apps split the form columns into a 3/9 split. In VT you used a 2/10 split. If I switch the VT columns to a 3/9 split they are the same width as an Exhibits form, which is what we want.

> Regarding font weight, library hours does not use a bold text on it's feedback form. Should that be fixed?

I don't think it's very critical. Most of our other apps don't use a heavier font weight for the field labels (this and the left- versus right-aligned labels on mobile are the main divergences among the forms, I think) so it seems more efficient to tackle all of them at one time, or do them individually when we're actually in a workcycle for a given application. (Also, technically I'm asking for a heavier font weight here, but not fully bold, just to be clear; I assume the `600` weight is available to us in our other applications but am not certain.)

> E if we want it to close, should we consider labeling it "Close" instead of "Cancel"? "Cancel" to me means, I don't want to proceed with whatever I was doing and I'd expect it to clear out.

We could consider using "Close" instead of "Clear" but I'd suggest doing so at some later date, when we can think about the feedback form more generally. Just because "Close" is a more accurate term when you are thinking about the mechanics of what the app is doing doesn't necessarily mean it's the most useful term for an end-user who doesn't think about the details an action they take has on the state of the application in the same way as a developer. And we've been using "Cancel" for years at this point. In any case, my concern for now is just getting the VT form in alignment with our other feedback forms. I'd rather consider changes that would affect the forms in all of our applications separately.

**Comment by jcoyne** [comment]
@ggeisler why do we show "Reporting from:..." to the user?  I think that's confusing as it is called out as if there is some action to take, but there isn't any. Why does this need to be on the page?

**Comment by ggeisler** [comment]
@jcoyne 

> why do we show "Reporting from:..." to the user? I think that's confusing as it is called out as if there is some action to take, but there isn't any. 

It might be confusing to you but it made sense to two of our UX designers and several product owners when we introduced it a handful of years ago and I'm not aware of any evidence since then showing that it's confusing to our end-users, which is who it is intended for. 

I don't agree that it's called out as if "there is some action to take." Similar info boxes are used all over the web without including any action for the user to take. The base version of the Bootstrap component itself doesn't include any user affordances.

> Why does this need to be on the page?

As I explained previously in this ticket:

> Displaying this prominently tells the user we know what page their feedback might relate to, and reduces the amount of clutter we used to get in the feedback responses where the user tries to describe (often not with the URL and ambiguously) what page they are on.

We added this to solve a problem years ago and it seems to have worked, so changing it because it doesn't make sense to a single developer seems unwarranted.

**Comment by jcoyne** [comment]
@ggeisler when I first was testing the feedback forms it was confusing to me, so I'm just speaking to my experience as a user.  I was unsure of why this was called out.  Although there are no affordances for action on the application, mearly calling it out says to me "You need to pay special attention to this" and I asked myself "why are they asking me to pay special attention?"

**Comment by ggeisler** [comment]
Right, we **are** telling the user to pay attention. We're saying, _We will know what page you are on right now, so don't waste time and clutter up your message with a long explanation trying to explain what you're looking at and how you got there_, which is what we were seeing often enough before that we decided we needed a way to mitigate it.
