### ISSUE TITLE
Reorder content inventory containers in ASpace

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#131]
I know the inventory description -> EAD work is still in progress but I noticed one thing with the recent update that I'll mention just in case it is relevant to the work to come: When there are containers that have dates as their label, if at all possible we should order those chronologically.

For example, see how this container is out of chronological order with its siblings:

<img width="443" alt="Screen Shot 2022-11-01 at 11 29 31 AM" src="https://user-images.githubusercontent.com/101482/199310975-9312cedc-2a4e-4a08-a2c6-d294e047950f.png">

This makes it harder for the user to scan the list and understand what is available.

This guideline is likely relevant to the "Audio recordings of proceedings" children, and any other grouping where we use dates as container labels.

**Comment by jcoyne** [comment]
Is there any structured data we could use to implement this or are we just trying to parse things that look like dates out of titles?

**Comment by cbeer** [comment]
I think we just used the order the components are arranged in the EAD file

**Comment by jcoyne** [comment]
So this can be a task for @laurensorensen to rearrange the items in Aspace?

**Comment by marlo-longley** [comment]
I read the docs, and there is something called Reorder Mode that should allow us to do this with drag and drop easily. @laurensorensen I know you are busy, let me know fi you want help doing this.

![Screen Shot 2022-11-01 at 18 36 31](https://user-images.githubusercontent.com/1328900/199355072-31eca1dc-3508-4739-977a-da4b76e7c5c0.png)

**Comment by ggeisler** [comment]
@marlo-longley That looks promising for doing this relatively easily.

While you are thinking about this, I suggest considering re-ordering the top-level containers (the series, I think) alphabetically (they almost are, but Exhibits and Audio are at the end), since as far as I know there is no other inherent order to them (just equal value intellectual groupings).

**Comment by marlo-longley** [comment]
Blocked per series by completed data upload.
Reordering, and then doing an upload will overwrite the reordering.

**Comment by thatbudakguy** [comment]
I manually re-ordered these using ArchivesSpace's reorder mode tool and it's reflected in the latest EAD (so should soon be visible in staging, once it's indexed). If anything else seems out of order, feel free to re-open this and let me know.
