### ISSUE TITLE
Omit the Online content filter box and icons

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#133]
This might be a debatable issue so if anyone thinks this is not a good idea, comment here and we can discuss before implementing.

Because every item in NTA is "online content", the "Show only online content" filter box we display on the collection page doesn't have any real value (in NTA it doesn't; generally I think it's very helpful). A user selecting that action just gets a search result of everything in the collection, so it's sort of false advertising and we're sort of encouraging the user to perform an action that doesn't really do what it suggests (it doesn't filter anything out).

Similarly, the online content icons, while normally useful in clueing the user into which items they'll be able to view directly through the site or links on the site, don't have any discriminatory value in NTA; when every item has the icon it is sort of meaningless.

The main argument I can see for keeping those elements in the NTA site is that a user who is familiar with other ArcLight sites might know and expect to see those elements when there is online content. If we omit them, that user might have the impression nothing in NTA is available online. (Also, if and when we add other collections to the NTA ArcLight instance, and if any of those collections are not 100% online content, we'd probably have to reverse this decision because then these elements do have value.)

However, we're going to have a custom homepage in NTA that through text and likely a couple of thumbnails, makes it pretty clear this is a digital collection. And a user who clicks around the site even a little bit should end up on a page with a viewer before too long.

My suggestion, then, is to omit the "Show only online content" filter box and the online content icons. That will remove a misleading feature (filter box) and unnecessary visual clutter (all of those icons).

I might be missing something but I think the affected locations are:

- Filter box on collection page
- Icons on sidebar content inventory tree
- Icons on parent container "Contents" results
- Icons on search result items

There's also an icon on the component show page but I believe that is removed in a pending PR.

 
<img width="1154" alt="Screen Shot 2022-11-01 at 11 44 21 AM" src="https://user-images.githubusercontent.com/101482/199316587-2a9fdc39-bbb2-428d-9549-4f4175af535a.png">

---

<img width="1154" alt="Screen Shot 2022-11-01 at 11 45 06 AM" src="https://user-images.githubusercontent.com/101482/199316597-8ff6c799-811f-42d2-a6ae-4fafcab8a7b0.png">

---

<img width="1154" alt="Screen Shot 2022-11-01 at 11 45 55 AM" src="https://user-images.githubusercontent.com/101482/199316600-686e50b6-70c5-4fd2-b0aa-f4ede33af018.png">

**Comment by jcoyne** [comment]
Blocked by https://github.com/projectblacklight/arclight/pull/1275

**Comment by jcoyne** [comment]
I believe this is complete.
