### ISSUE TITLE
Link SUL logo to library website

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#134]
Broken out from #66 
Change the link for part "A" -- currently it points to the app's homepage

A: Replace the "ArcLight" logo text with the SUL logo image - same version used in Exhibits. This should be linked to go to https://library.stanford.edu/ (which is different than Exhibits).

**Comment by jcoyne** [comment]
Blocked by https://github.com/projectblacklight/blacklight/pull/2865

**Comment by jcoyne** [comment]
Now blocked by https://github.com/projectblacklight/arclight/pull/1270

**Comment by jcoyne** [comment]
Blocked by https://github.com/projectblacklight/blacklight/pull/2889
