### ISSUE TITLE
Confirm we can provide multiple language transcripts in media viewer downloads

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#139]
Once video transcripts are accessioned we can confirm this.

**Comment by marlo-longley** [comment]
@laurensorensen now that the videos are accessioned, let's do this :)

**Comment by laurensorensen** [comment]
I looked a a few examples and all looks good to go. Since I can't navigate on virtualtribunals-stage, I can't see if they are appearing in the embedded viewer - I imagine confirming this is our next step?

**Comment by laurensorensen** [comment]
I looked at examples and all works well - Hannah said there shouldn't be anything needed insofar as updating the embedded viewer, but I'll confirm how it looks after I can access the content inventory on stage.

**Comment by marlo-longley** [comment]
Confirmed. See https://vt-stage-a.stanford.edu/catalog/mt839rq8746aspace_4a23a5fefbd3bfc65d134be60a58b5b6 (
H-5247).
