### ISSUE TITLE
Create facet and display in component view: Document format = dc:format

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#145]
Ref #29 

@laurensorensen is that this?

```
  <odd id="aspace_b10a4f9a5f187f68bc7c0b93e96694b4">
    <head>General</head>
    <p>16" Aluminum Presto Instantaneous Disc</p>
  </odd>
```

**Comment by laurensorensen** [comment]
Yes, correct!

**Comment by marlo-longley** [comment]
dc:format is note with Type General if it exists (snippet) -- or else it's the subseries title.

**Comment by marlo-longley** [comment]
While indexing this, we also need to make sure it's displayed in the component view as it's currently missing, e.g. ""16" Aluminum Presto Instantaneous Disc"" should be in this record


![Image](https://user-images.githubusercontent.com/1328900/201222348-2d652625-77bd-47b7-bb35-fc93558b43c3.png)

**Comment by marlo-longley** [comment]
We can count on the <odd> for this

**Comment by jcoyne** [comment]
> We can count on the for this 
@marlo-longley ???

**Comment by marlo-longley** [comment]
Closing in favor clearer tickets.
