### ISSUE TITLE
Fulltext search of OCR content: Write custom indexer

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#153]
Ref #146  -- Step 2:

Notes:
- We need to be careful of the nested component indexing
-  Use similar pattern as folio traject config -- make a new config that imports all of Arclight's and changes a few details. 
- The fulltext Solr field in Exhibits may be a multi-valued field with entries per page -- we don't care and are going to have a single valued field.

**Comment by jcoyne** [comment]
Implementers may want to look at https://github.com/projectblacklight/arclight/pull/1268
