### ISSUE TITLE
Investigate the extent and quality of date data

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#157]
Do we have any information at granularity higher than Year?
Lauren: we think we have 5000 records.

How will we handle items that have start and end dates?

**Comment by laurensorensen** [comment]
There are 5 date fields, and it looks like most are in columns Q and U. Here is the breakdown for dates entered (9629 rows total): 

Column Q: 4268 blanks = 5361 with date data	
Column R: 9584 blanks = 45 with date data
Column S: 9618 blanks = 11 with date data
Column T: 9623 blanks = 6 with date data
Column U: 5206 blanks = 4423 with date data

So it looks like at least one date for one record, so it is useful to have the day-level faceting, if feasible for this work cycle. 

At the minimum, we'll need month-year faceting. There are reasons for users to want to search for days, though - e.g. if they knew a relative testified or an exhibit was presented on a certain day, they could look up the exact date recording, or the documents during that time.  

I am out the rest of the day (Fri) but I'll check back Monday on this. Thanks!

**Comment by marlo-longley** [comment]
Most records that are documents have Q data
Most records that are disc recordings have R data

**Comment by marlo-longley** [comment]
We likely will classify all dates as creation dates because we lack context
