### ISSUE TITLE
Unclicking bookmark results in JS error

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#159]
And the text next to the bookmark checkbox gets stuck at "Saving..."

![Screen Shot 2022-11-04 at 17 16 56](https://user-images.githubusercontent.com/1328900/200076295-c992d60c-fdac-437e-a157-861a439defb8.png)

**Comment by jcoyne** [comment]
This is actually a problem in Blacklight, but I don't see a ticket there.

**Comment by marlo-longley** [comment]
@jcoyne Thanks -- I can open a ticket there.

**Comment by marlo-longley** [comment]
Closing in favor of https://github.com/projectblacklight/blacklight/issues/2871
