### ISSUE TITLE
Customize search result item display

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#161]
The suggestions below are NTA-specific adjustments to improve the search results view based on the unique aspects of the NTA project. Some of these might depend on further progress on indexing or need more discussion. 

## Option A - omit document creator and breadcrumb
This is not the preferred option, but at a minimum I suggest we update the result item display to:

<img width="900" alt="Screen Shot 2022-11-04 at 3 01 51 PM" src="https://user-images.githubusercontent.com/101482/200086376-96c16353-d244-42f6-af97-142430f4fdeb.png">

- **A: Omit the "document creator"** - this is the same ("International Military Tribunal") for every NTA item so has no value to the user
- **B: Omit the repository node from the search result breadcrumb** - with only repository we're not displaying the repository elsewhere in the NTA site, so it makes sense to omit it here as well. Since the breadcrumb would start with the collection node, it would be ideal to **use the collection icon**, as shown in the mockup below.
- The text blocks in the screenshot "Scope and Contents PLACEHOLDER" and "The collection in the Virtual Tribunal platform ..." should **remain** (I think these are the `al-document-abstract-or-scope` element).

So the updated display would look something like:

<img width="1157" alt="Screen Shot 2022-11-04 at 3 22 55 PM" src="https://user-images.githubusercontent.com/101482/200086515-dbdb8cbc-8b55-4fd5-81b4-aa41761955b8.png">

## Option B - display abstract and document attributes
More useful to the user would be to do what's suggested in Option A plus provide some additional information about the document that would help the user both understand the document a bit better and possibly use the additional information to pivot to to another search using a document attribute of interest:

<img width="1157" alt="Screen Shot 2022-11-04 at 3 07 34 PM" src="https://user-images.githubusercontent.com/101482/200086682-d734c4f0-ef42-4720-abd0-e67a44fba3dc.png">

- **Omit the "document creator" as in Option A.**
- **B: Omit the breadcrumb entirely** -  since the document attributes include document type, which is also the item's parent series, the breadcrumb is mostly redundant and makes for a more cluttered view of the item.
- **C: Add a row of document attributes** - this is completely custom for NTA but if feasible I think would provide a lot of value for the user. The attributes would improve the issue we have with duplicate document titles (the item id will help clarify they are distinct items when two items with the same title are in close proximity in the results). And linking the values of the other attributes will enable the user to quickly explore documents associated with one of those values. (Ignore the fact that the bullet icon separating the attributes is red; it should just be the normal body text color.)

### Document attributes details (C)
- Item ID - Every document in the inventory has a unique item ID `dc:identifier` that could be very useful to the user in keeping track of documents of interest and distinguishing between documents with the same title (which comes up sometimes). This looks like it is in the `<unitid>` element of the EAD for components at the file level.
- Date - We're still figuring out the date issues, but this would be a single date associated with the document. Ideally it's linked so it would lead to a search result of all documents with a matching date.
- Extent - The mockup examples are number of pages, but I think for media these can be a duration of time. This is `dcterms:extent` in the original data and appears to be in the `<physfacet>` element of the EAD.
- Document type - Unclear to me if we are using the original `dc:type` or the parent series label, but this would ideally be a linked version of that so the user could navigate to all documents with a matching document type.
- Language - I think this could be multi-valued? Ideally linked to a single value language search result.

Text styling for the document attributes row is `15px` (or `0.938rem`) font-size, using the normal NTA link color for the attribute values we can link.

## Likely future related work
Omit the compact view of results:

<img width="1001" alt="Screen Shot 2022-11-04 at 4 11 42 PM" src="https://user-images.githubusercontent.com/101482/200087738-6014517e-e29a-4242-930d-08730ce18e01.png">

  
I'd feel safer waiting until more of the NTA documents are available, the indexing is more complete, and full-text search is working before making this decision, but I suspect that in the end, for the NTA collection, the compact view of results won't add much value. If that turns out to be the case, it would be better to omit the option than enable the user to take an action that provides no significant value.

**Comment by jcoyne** [comment]
Blockec by https://github.com/projectblacklight/arclight/pull/1277
