### ISSUE TITLE
Adjust sizing of topbar elements

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#168]
This applies to both the VT landing page topbar and the NTA site topbar. The goal is to reduce the height of the topbar and make it more visually similar to other SUL application topbars.

<img width="1174" alt="Screen Shot 2022-11-07 at 12 15 27 PM" src="https://user-images.githubusercontent.com/101482/200395351-3c13bb04-e6f5-4fc0-b7ca-884ef816f09d.png">

- Reduce the font-size of the topbar menu items to `15px` (or `0.938rem`). That's what we use for Exhibits and other applications.
- Reduce the size of the SUL logo to `35px` - it's currently `50px`. Hopefully this adjustment will improve the vertical alignment of the logo, which currently isn't vertically centered/sits too high.

**Comment by jcoyne** [comment]
Size change is blocked by https://github.com/projectblacklight/blacklight/pull/2882
