### ISSUE TITLE
Find out why uploaded data is missing in ASpace

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#170]
I'm able to find that all fields mapped over from the original data except for:

**Language fields**
This seems to be a problem with the uploader?
Do we need to set settings in ASpace when we are adding fields/columns to spreadsheet?

**Box information (e.g. Box 11)**

**Dates**
Should we use date begin instead of date label for single dates?

Example: H-2770
Should have multiple languages, Box info, and dates -- missing

**Comment by laurensorensen** [comment]
I mapped the existing codes to readable word here: 
https://docs.google.com/spreadsheets/d/18CDb4KKAgcmV2ctJc-FZKMVLJUXElS6djRPfNN4q9Zk/edit#gid=0
