### ISSUE TITLE
Create VT specific index config

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#172]
Use similar pattern as folio traject config -- make a new config that imports all of Arclight's and changes a few details

Ref https://github.com/projectblacklight/arclight/pull/1268

**Comment by jcoyne** [comment]
@marlo-longley isn't this part of #162?  Can we close this as a duplicate?

**Comment by marlo-longley** [comment]
Hey @jcoyne -- not sure I understand. This ticket is just setting up the basic files like in this PR https://github.com/sul-dlss/vt-arclight/pull/173. It is not implementing any specific indexing rules or patterns yet.
