### ISSUE TITLE
Improve alignment of "view more" button in inventory tree

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#176]
This likely should be done in core ArcLight but none of the fixtures in my local ArcLight environment display this text/view more button, so I can't easily verify that the issue exists there.

The "view more" link in the Collection contents inventory tree is a button with default padding on all sides. The left padding makes it indent so it doesn't line up on the left-side with the text it is associated with:

<img width="501" alt="Screen Shot 2022-11-07 at 5 09 43 PM" src="https://user-images.githubusercontent.com/101482/200442663-98174862-5f29-4dfb-b71f-8c1fd9f89a8c.png">

---

I suggest removing that left padding so the button text is left-aligned with the text above it:

<img width="501" alt="Screen Shot 2022-11-07 at 5 10 17 PM" src="https://user-images.githubusercontent.com/101482/200442739-10f97c4a-e118-43fe-b778-d7ecf88255ca.png">

**Comment by jcoyne** [comment]
This is complete.
