### ISSUE TITLE
Hierarchical date facet?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#184]
A developer might have to explore how technically feasible this is, but I think a hierarchical facet for date could potentially be very useful. I know we heard from some potential users that exploring by date or wanting to see everything on a specific date would be helpful and this way of handling the date facet would enable that.

Note we do have hierarchical facets in DLME ([Type](https://dlmenetwork.org/library/catalog?f%5Bcho_type_facet.en_ssim%5D%5B%5D=Image)) and Searchworks ([Call number](https://searchworks.stanford.edu/?f%5Baccess_facet%5D%5B%5D=Online&f%5Bcallnum_facet_hsim%5D%5B%5D=Dewey+Classification&f%5Bcallnum_facet_hsim%5D%5B%5D=Dewey+Classification%7C100s+-+Philosophy%7C100s+-+Philosophy)). DLME has only two levels but Searchworks has three levels, and thus is similar to the goal for NTA.

As with the DLME and Searchworks implementations, the idea is that the user could select a value at any level of the hierarchy (e.g., can select a year value, without expanding the hierarchy, to facet on all items with a date in that year; same with a month in a given year, after that year has been expanded).

And of course the user could also just expand a year and then a month, before selecting a day to find only records with that exact date value.

## Year
<img width="753" alt="Screen Shot 2022-11-09 at 1 57 37 PM" src="https://user-images.githubusercontent.com/101482/200952686-ae0b3c5d-8884-4595-a528-769013301c71.png">

## Month
I'm suggesting in the mockups that we use a display value for the month that is probably different from the source/indexed value, but it would be much more user friendly than using ("01", "02", etc.). This display format would only be used in the Date facet (records would still show the source "1945-02-05" format).

<img width="799" alt="Screen Shot 2022-11-09 at 2 00 11 PM" src="https://user-images.githubusercontent.com/101482/200952796-8108418f-6f08-4712-82a8-2395d0abd6cd.png">

## Day
Again, I'm suggesting in the mockups that we use a display value for day that is different from the source/indexed value, but a more user friendly format. This display format would only be used in the Date facet (records would still show the source "1945-02-05" format).

<img width="636" alt="Screen Shot 2022-11-09 at 2 01 14 PM" src="https://user-images.githubusercontent.com/101482/200952820-db3d79bc-5598-4d34-8270-55fc07db219e.png">

## Styling details
- Expand icon: https://icons.getbootstrap.com/icons/plus-square/
- Minus icon: https://icons.getbootstrap.com/icons/dash-square/
- Icon color: -secondary

**Comment by ggeisler** [comment]
Yeah I guess if there was a way to see all the possible item <-> date value associations there is more analysis that could be done. I'm not sure we have the data to do that yet? Maybe I could figure out more by digging into @laurensorensen's source data spreadsheet, though.

If a record has a date range, could we index that item with every date in the range? Even if we can, I'm not certain that makes sense without seeing what sort of items have ranges (i.e., better understand what a date range means in the context of the collection).

**Comment by cbeer** [comment]
Some range examples from our EAD (and.. it seems like we always have ranges):
1946-06-10/1946-06-10
1946-08-27/1946-08-31
1945-11-20/1946-10-01 (collection)
1945-10-09/1946-10-01 (item: Minutes of International Military Tribunal Meetings, 9 Oct 1945 - 1 Oct 1946, Nos. 1-100)

I guess it's not the end of the world if a couple items show up for every possible date? 🤷‍♂️

**Comment by ggeisler** [comment]
Thanks for the examples @cbeer. For some reason I have a habit of just referring to Lauren's metadata spreadsheet when looking at item metadata, instead of using the EAD to find them.

I've gone through the current EAD and think I found every distinct type of `<unitdate>` expressed (since there are a lot more records not yet in the EAD, there could be more variants, but this looks like it potentially could capture all variants).

I definitely am interested in hearing any counter arguments, but I do think indexing an item for every day in its range makes sense. If a user selects a specific day via the facet and an item has begin and end dates spanning that day, it does seem like that document is relevant to their query and should be returned. (They might have to scroll through the document PDF to find the part that is relevant to the specific query day, but it seems like the document could be relevant.) Based on the small sample in the EAD, there actually aren't a ton of items with true date ranges (as you noted, every single `normal` attribute looks like a range, but usually both sides of the slash are the same value). Though I admit that could change when we have the full corpus of documents.

### Date variants
It looks like if the `normal` attribute includes the same value before and after the separating slash, we just index the first value (Single date and Multiple single date variants below).

If the `normal` attribute includes different values before and after the separating slash, we index every date between those values, inclusive (Multiple single dates variant).

- **Single date** (H-1092): 
	- `<unitdate normal="1946-05-20/1946-05-20" type="inclusive">1946-05-20</unitdate>`
	- Item would be indexed as 1946 > May > 20th
- **Multiple single dates** (H-5194): 
	- `<unitdate normal="1946-06-18/1946-06-18" type="inclusive">1946-06-18</unitdate>`
	- `<unitdate normal="1946-06-19/1946-06-19" type="inclusive">1946-06-19</unitdate>`
	- `<unitdate normal="1946-06-20/1946-06-20" type="inclusive">1946-06-20</unitdate>`
	- `<unitdate normal="1946-06-21/1946-06-21" type="inclusive">1946-06-21</unitdate>`
	- Item would be indexed as 1946 > June > 18th; 1946 > June > 19th; 1946 > June > 20th; 1946 > June > 21st
- **Date range** (H-1216): 
	- `<unitdate normal="1946-08-27/1946-08-31" type="inclusive">1946-08-27-1946-08-31</unitdate>`
	- Item would be indexed as 1946 > August > 27th; 1946 > August > 28th; 1946 > August > 29th; 1946 > August > 30th; 1946 > August > 31st 
- **Outlier year** (H-0000 - this is the entire inventory PDF):
	- `<unitdate normal="1950-05-06/1950-05-06" type="inclusive">1950-05-06</unitdate>`
	- This is the single date variant, but unlike (everything? most everything?) else, its year isn't 1945 or 1946, it's 1950. I think that is okay. Only one result might be returned for each level, but it's accurate and consistent so I don't think would be confusing.
	- Item would be indexed as 1950 > May > 6th

### Date/time variants
We can drop the time component of the date/time value for this facet, which I believe means we can then treat them as Single date and Multiple single date variants as described above.

Perhaps a tricky difference is unlike the Multiple single date variant described above, here it appears that often (or always?) the second date/time instance becomes duplicative of the first instance, so despite having multiple `<unitdate>` instances, the item would only be indexed for one date.

- **Single date/time** (H-2766): 
	- `<unitdate normal="1946-10-04T00:00:00+00:00/1946-10-04T00:00:00+00:00" type="inclusive">1946-10-04T00:00:00+00:00</unitdate>`
	- Item would be indexed as 1946 > October > 4th 
- **Multiple date/time** (H-5260_1732A_1): 
	- `<unitdate normal="1946-04-01T00:00:00+00:00/1946-04-01T00:00:00+00:00" type="inclusive">1946-04-01T00:00:00+00:00</unitdate>`
	- `<unitdate normal="1946-04-01T10:10+01:00/1946-04-01T10:25+01:00" type="inclusive">1946-04-01T10:10+01:00-1946-04-01T10:25+01:00</unitdate>`
	- Item would be indexed as 1946 > April > 4th

**Comment by marlo-longley** [comment]
@ggeisler @laurensorensen @cbeer I just had a call with Lauren where we were talking about datetime display (not faceting specifically) and she let me know that she is working on splitting the datetimes that are ranges (split on a slash /) into distinct fields. I'm not sure the status of this work or conversation but it seemed important to note that dates of this style `<unitdate normal="1946-04-01T10:10+01:00/1946-04-01T10:25+01:00" type="inclusive">1946-04-01T10:10+01:00-1946-04-01T10:25+01:00</unitdate>` that are combined as analyzed by Gary above may become obsolete soon pending work by Lauren. Hoping she can chime in.

**Comment by laurensorensen** [comment]
There is a start date and end date so Marlo is correct that I am splitting those that look like this: 1946-04-01T10:10+01:00/1946-04-01T10:25+01:00

I would like to keep the time information in the component view, but it isn't necessary for faceting. 

There are many that look like this and have a range. Some have ranges that have to do with only time, but others that are like this: 1946-04-01/1946-04-10 

But like Marlo said, I'm splitting that data so that it fits into the uploader spreadsheet's separate start and end dates.

**Comment by laurensorensen** [comment]
Gary is right that "second date/time instance becomes duplicative of the first instance." Understandable that this will be tricky...

**Comment by marlo-longley** [comment]
I wanted to update Gary's analysis as the types of date values have changed. 

### 1. Date: does not contain type attribute in XML
**Single date (H-1092)** (note: no longer contains type=inclusive)
```xml
<unitdate certainty="inferred" normal="1946-05-20/1946-05-20">1946-05-20</unitdate>
```
**Outlier year (H-0000)** (follows same structure as Single date above)
```xml
<unitdate certainty="inferred" normal="1950-05-06/1950-05-06">1950-05-06</unitdate>
```

**Multiple single dates (H-5194):** (note: no longer contains type=inclusive)
```xml
<unitdate certainty="inferred" normal="1946-06-18/1946-06-18">1946-06-18</unitdate>
<unitdate certainty="inferred" normal="1946-06-19/1946-06-19">1946-06-19</unitdate>
<unitdate certainty="inferred" normal="1946-06-20/1946-06-20">1946-06-20</unitdate>
<unitdate certainty="inferred" normal="1946-06-21/1946-06-21">1946-06-21</unitdate>
```

### 2. Date range: contains type=inclusive attribute
**Date range (H-1216)** (same as Gary's analysis)
```xml
<unitdate certainty="inferred" normal="1946-08-27/1946-08-31" type="inclusive">1946-08-27-1946-08-31</unitdate> 
```
### 3. Datetime range
-- Though Gary identified some "single" datetimes above, once we remediated the data to remove times that were all zeros, `T00:00:00`, these no longer exist in our collection. The only remaining datetime format is:

**Multiple date/time (H-5260_1732A_1)**
```xml
<unitdate certainty="inferred" normal="1946-04-01T10:10+01:00/1946-04-01T10:25+01:00" type="inclusive">1946-04-01T10:10+01:00-1946-04-01T10:25+01:00</unitdate>
```

I believe it is safe to conclude that only ranges have `type=inclusive` in our data, whether they are dates or datetimes.

**Comment by marlo-longley** [comment]
Note: we should use the value in the `normal` attribute as the definitive source for this work.
