### ISSUE TITLE
Gather sample queries from NTA Spotlight analytics

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#185]
This will help guide us with how to calibrate search relevancy

**Comment by laurensorensen** [comment]
Here are the most popular search phrases/terms and number of hits from Google Analytics from September 2020 to Oct 31 2022:

https://docs.google.com/spreadsheets/d/1GcQnsKyq_UEY4hboU4edmClLru0um1vpQNpxN6iN8CI/edit#gid=0
