### ISSUE TITLE
Right-align title area bookmark control

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#212]
I'm not sure if this is still being sorted out through ArcLight core or not, but it looks like we're not right-aligning the bookmark control in the component show page title area as intended:

<img width="796" alt="Screen Shot 2022-11-14 at 10 45 38 AM" src="https://user-images.githubusercontent.com/101482/201730297-42558ac9-0e4f-4e1a-bffd-1fc1ee158935.png">

The bookmark control should always be in the same place, at the right-edge of the content area, even if the item title is short.

https://virtualtribunals-stage.stanford.edu/catalog/mt839rq8746aspace_b66ace76e1267794a7cded73a1a15e78

**Comment by marlo-longley** [comment]
Fixed by https://github.com/projectblacklight/arclight/pull/1350
