### ISSUE TITLE
Breadcrumb icons show up one step late

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#221]
I originally filed this in ArcLight core and it appears closed and merged: https://github.com/projectblacklight/arclight/issues/1238

But I still see the problem in VT ArcLight:

At the collection level, no collection icon:

<img width="1166" alt="Screen Shot 2022-11-15 at 10 33 02 AM" src="https://user-images.githubusercontent.com/101482/201987946-cb1b39fc-6a5e-4cea-857a-2731831a168b.png">

---

Going to the series level, the collection icon appears, but not the arrow that should precede the series node:

<img width="1166" alt="Screen Shot 2022-11-15 at 10 33 22 AM" src="https://user-images.githubusercontent.com/101482/201988093-d837df24-c79a-4674-a078-1d4582f316aa.png">

---

And then going to the subseries level the series arrow appears:

<img width="1166" alt="Screen Shot 2022-11-15 at 10 33 47 AM" src="https://user-images.githubusercontent.com/101482/201988164-b02b0882-9f12-4c96-a5e8-e09f6d61da5d.png">

**Comment by jcoyne** [comment]
@ggeisler, et. al. This is because we aren't using Arclight's component here. We have our own component that replaces the one from Arclight.
