### ISSUE TITLE
Collection info box buttons should be vertically aligned

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#222]
I don't have ArcLight core running, so I'm not sure if this is an ArcLight core issue or specific to NTA (maybe NTA-specific because we added the download icon here?) but the two buttons in the Collection info box are out of vertical alignment. 

It's fairly subtle but pretty obvious once you know it's there:

<img width="867" alt="Screen Shot 2022-11-15 at 10 41 59 AM" src="https://user-images.githubusercontent.com/101482/201989570-bd278ec2-1c7a-4ac1-b53f-dca05d946085.png">

The buttons look to be the same height so it's just something about how they are vertically positioned.

**Comment by jcoyne** [comment]
I'm unable to duplicate this.  Is it still a problem @ggeisler ?

![Image](https://user-images.githubusercontent.com/92044/202295981-22aa29db-73d8-4546-8f16-9a21e1a77957.png)

**Comment by ggeisler** [comment]
@jcoyne Interesting. Yes, I still see the issue, in Firefox and Chrome. However, it does look fine in Safari (examples are in the collapsed mobile viewport but they all the same as in desktop viewport):

<img width="967" alt="Screen Shot 2022-11-16 at 2 32 32 PM" src="https://user-images.githubusercontent.com/101482/202299498-3b3f163d-8084-441d-b483-9f79a18cd8e0.png">

Maybe we more data points.

@marlo-longley or @thatbudakguy can you tell us if you see this button alignment issue?

**Comment by jcoyne** [comment]
FWIW, I was looking in Firefox 106.0.5 and I didn't see the issue.

**Comment by ggeisler** [comment]
I was on 106.0.3 and just upgraded to 107.0 and still see it. If we get confirmation that other people don't see it I'll just pretend I don't see it and close this.

**Comment by cbeer** [comment]
I see it. I'm guessing we probably need wrap those buttons in a div to get them aligned nice?

**Comment by thatbudakguy** [comment]
in staging, I don't see it on firefox 108.0b2, but i do see it on chrome 110.0.5424.0 and safari release 156 (Safari 16.4, WebKit 17615.1.8.5)
