### ISSUE TITLE
Add item-level content warning

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#232]
Discussion about this is in #190, but this is the more actionable part.

For components that are either images or moving images (video) only, on the component show page we want to insert this content warning before the viewer. (I'm not certain how we determine if the component is an image or a moving image at this point; I think we're planning to use the `edm:type` field but I don't think that field is encoded in the EAD yet, so this ticket might not be completely actionable until the data is further along.)

<img width="565" alt="202255728-882c5a77-a73b-41a1-8bb5-08c2914ab8dc" src="https://user-images.githubusercontent.com/101482/202532840-3073e97e-60b3-46ab-81f6-3419e728f468.png">

---

Text: `Content warning: Imagery and language presented in this archival material may be harmful or traumatizing to some audiences.`

Styling: For now at least, I think we can just copy the [alert component we use on the home page](https://github.com/sul-dlss/vt-arclight/blob/178e48a8a7596c22409293ea8df3d146546775d7/app/views/catalog/_home_text.html.erb#L3) for the general content warning:

```
<div class="alert global-warning">
  <span>Content warning:</span> Imagery and language presented in this archival material may be harmful or traumatizing to some audiences.
</div>
```

**Comment by marlo-longley** [comment]
Images and Moving images are indexed with Media format (see #259) -- we can use this to distinguish the type of content that needs the warning.
