### ISSUE TITLE
Index into extent field

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/vt-arclight#252]
Currently extent is indexed in arclight in these locations:
* https://github.com/projectblacklight/arclight/blob/f47ed19eaeea95e2e8969ee42cd63836d3504302/lib/arclight/traject/ead2_config.rb#L195
* https://github.com/projectblacklight/arclight/blob/6e57873176ced74a0109ad86f5a32f2d4b9bfd0b/lib/arclight/traject/ead2_component_config.rb#L162-L163

However in #217  @ggeisler specifies:

> We currently display an Extent field on the item level show page, but it is not using the values I believe we want to use. It currently appears to concatenate the `<physdesc><extent altrender="materialtype spaceoccupied">` and `<physdesc><extent altrender="carrier">` values. Instead, I suggest we use the `<physdesc><physfacet>` value, which is much more useful at the item level (tells the user how many pages a document is, or how long a media object is, rather than just saying "1 items(s)").

**Comment by laurensorensen** [comment]
In case this is helpful - in #290 (more up to date than #217) Gary explains that the extent display is fine as is: 

"Extent: It looks like we're now displaying something like 1 item(s) and 20 pages for item-level components, which is fine. My mockup only includes the pages part, but the current approach is okay, especially if it displays something useful at the parent container levels."

**Comment by thatbudakguy** [comment]
Closing, since I think we meet these requirements:
- Items say e.g. "1 item(s) and 120 pages"
- all other components say the number of total items they contain, e.g. "3240 item(s)"
