### ISSUE TITLE
Index Media format at component level

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#254]
[See crosswalk sheet "Arclight"](https://docs.google.com/spreadsheets/d/1a_doAL669TXXzadv3UC07oOAv4jS7cVCsE4wfgqPag0/edit#gid=330042512)

The xpath at the component level is: `/did/container/@label` Example component-level EAD. 

```xml
<c id="aspace_12f6e64088563a824fd69a6e54ad4403" level="item">
  ...
  <did>
      ...
      <container id="aspace_c2bf9345f185b33b546483366ede7b7e" label="Text" type="box">9</container>
   </did>
</c>
```

In this example "Text" is the Media format. Possible values include:

- Images
- Text
- Sound
- Moving image

This attribute is not indexed in AL Core and will need custom indexing.

**Comment by jcoyne** [comment]
@marlo-longley I also see "Mixed Materials".  Is that allowed?
https://github.com/sul-dlss/vt-arclight/blob/main/public/data/mt839rq8746.xml#L11900

**Comment by marlo-longley** [comment]
Thanks @jcoyne ! I believe in the latest EAD the values will be updated. The xpath will be the same. You won't get Mixed Materials anymore.

**Comment by thatbudakguy** [comment]
no more "mixed materials" with latest EAD:

![Screen Shot 2022-11-21 at 14 17 33](https://user-images.githubusercontent.com/4924494/203169409-90c5db04-4232-4aa9-8c0a-828aff397232.png)
