### ISSUE TITLE
Index Resource format at the component level

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#256]
[See crosswalk sheet "Arclight"](https://docs.google.com/spreadsheets/d/1a_doAL669TXXzadv3UC07oOAv4jS7cVCsE4wfgqPag0/edit#gid=330042512)

The xpath at the component level is: `/did/physdesc/physfacet` Example component-level EAD.

```xml
<c id="aspace_12f6e64088563a824fd69a6e54ad4403" level="item">
  ...  
  <did>
     ...
     <physdesc altrender="whole">
        ...
        <physfacet>Folders</physfacet>
      </physdesc>
   </did>
</c>
```

In this example, "Folders" is the Document format. Here are the possible values of Document format:
- 16” aluminum Presto instantaneous discs
- Books
- Envelopes
- Film
- Film in box
- Film in can
- Folders
- Loose leaf folders
- Loose leaf photo albums
- Microfilm
- Package
- Package photostats
- Photo albums
- Volumes
- Volumes of bound newspapers

This is not indexed by AL core so we need to write custom indexing.

**Comment by jcoyne** [comment]
@marlo-longley when I tried this I got values like "77 pages".  https://github.com/sul-dlss/vt-arclight/blob/main/public/data/mt839rq8746.xml#L127  Is this right?

**Comment by marlo-longley** [comment]
@jcoyne Thanks for catching that. In our latest EAD, I'm not seeing that (pending #250 -- full QA of the data currently happening). We have moved things like "77 pages" into the extent attribute so you will the following. Basically this xpath should be correct even if current contents are wrong.

```xml
<physdesc altrender="whole">
     <extent altrender="materialtype spaceoccupied">1 item(s)</extent>
         <extent altrender="carrier">77 pages</extent>
      <physfacet>Folders</physfacet>
</physdesc>
```

**Comment by marlo-longley** [comment]
@jcoyne sorry, but I was just informed this renamed to Resource format.

**Comment by thatbudakguy** [comment]
here's what we indexed with latest EAD for "resource format":
![Screen Shot 2022-11-21 at 14 08 50](https://user-images.githubusercontent.com/4924494/203167945-bfa41219-5c89-451f-94fd-98ee52fab3fc.png)
