### ISSUE TITLE
Index Resource type at component level

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#258]
This may be the trickiest indexing ticket, because we cannot get this data in the EAD at the component level. We must infer it from an item's parent at the "Series" level. Here is an example of the EAD. In this example, "Trial briefs" is the component level Resource type. The component with title **"Defense for Hess. Part 1" has a Document type of "Trial briefs".** That data is not available anywhere in the component level EAD.

```xml
<c id="aspace_89fdcaa153cb4e1e55fb285d6b1a1a87" level="series">
    <did>
      <unittitle>Trial briefs</unittitle>
      ...
    </did>
    <c id="aspace_2ae07606029cba19a46fddc3fb24fda7" level="subseries">
      <did>
        <unittitle>Folders</unittitle>
        ...
      </did>
      <c id="aspace_e3673881a6dc941132ce84e15e5c76b9" level="item">
          <did>
            <unittitle>Defense for Hess. Part 1</unittitle>
            ...
          </did>
        </c>
    </c>
</c>

```

The possible values for Document type are:

- Audio recordings of proceedings
- Document books
- Empty folder
- Exhibits
- Final pleas and clemency pleas
- Indictments
- Judgments, dissenting opinions, and sentences
- Lists, indices, and miscellaneous6
- Minutes of tribunal meetings.
- Official commission transcripts  
- Official court transcripts
- Rules, rulings, and orders
- Statements and speeches
- Trial briefs

We need to write custom indexing for this.

**Comment by jcoyne** [comment]
@marlo-longley in this example should aspace_2ae07606029cba19a46fddc3fb24fda7 have a Document type or should only aspace_e3673881a6dc941132ce84e15e5c76b9?

**Comment by marlo-longley** [comment]
@jcoyne good question. I believe only the terminal component/node/item should have a document type.

@laurensorensen can you confirm that Sub-Series and Record Groups should not have Document type, i.e. only Items should have Document type?

**Comment by jcoyne** [comment]
@marlo-longley @laurensorensen what about components where `@level='file'`?

**Comment by marlo-longley** [comment]
@jcoyne file = resource group :) Will be changing in latest EAD.

**Comment by marlo-longley** [comment]
Also, I was just informed that this is now named Resource type.

**Comment by laurensorensen** [comment]
Correct, Sub-Series and Record Groups should not have Document type
