### ISSUE TITLE
Reindex latest EAD and transcripts

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#269]
1. Deploy latest main branch with EAD from #267
2. Harvest the files based on latest EAD for latest transcripts and put them on stage and prod servers
3. Run the index task on the servers

**Comment by jcoyne** [comment]
@marlo-longley Do we want to add?
> 2.5 Delete the old data from Solr

**Comment by marlo-longley** [comment]
All steps including 2.5 done on stage and prod.

There are 5249 .txt files in `/vt/shared/data/fulltext` on both servers. I ran indexing.

Searching for text from transcripts in the UI does not return results. There may be a problem.

**Comment by marlo-longley** [comment]
Now blocked by #280

**Comment by marlo-longley** [comment]
Closing, we can deal with the rest of this in #280
