### ISSUE TITLE
Set up honeybadger monitoring

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/vt-arclight#276]
This is a core part of making the app production-ready.

**Comment by laurensorensen** [comment]
Please add myself and @hannahfrost to the list of people who get notifications (or if that's not a thing that's done, if we can be added to the slack channel or get access to the place where notifications are received, that would work too).

**Comment by marlo-longley** [comment]
Closing; Hannah and Lauren will be notified on the nuremburg-trial-archive slack channel of any issues.
