### ISSUE TITLE
Numbers in box next to Series in sidebar navigator - isn't clear what they are expressing

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#277]
The numbers next to the Series level in Collection Navigator makes it seem like there are items below it instead of a sub-level, and it's not decipherable from the perspective of someone coming to the site unfamiliar with the "levels" of EAD. 

Is it possible to format like this instead: [Name of series] [1 Sub-series] [10 Record groups] [3400 items]

FWIW I'd say this is low priority as we don't have direct feedback from users. 

<img width="411" alt="Screen Shot 2022-11-22 at 10 28 37 AM" src="https://user-images.githubusercontent.com/3269689/203393826-a9037114-fbad-4e26-88f1-d842208938b7.png">

**Comment by ggeisler** [comment]
@laurensorensen I'd strongly advise against this. That would make the UI extremely busy with all the extra words and numbers. And, as you said, we don't even know if there is a problem this would be solving. 

I'd suggest we stick with the default ArcLight display for this we're currently using (as Duke has, with many collections having nested trees, and Sean did not indicate he's heard any problems from users related to this). We can always adjust in the future if we find out that users are confused.

Even if a user is initially unsure what the item badges mean, they will likely learn pretty quickly as they use the application. That's a reasonable tradeoff versus cluttering the UI with additional text and numbers that most users won't need after using the app a little bit.

**Comment by laurensorensen** [comment]
Ok great thanks for commenting on this Gary, I appreciate it! This all makes sense. I'll close this ticket.
