### ISSUE TITLE
Explore feasibility of offering OCR .txt files for download

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#278]
Text documents use a different viewer (Mirador) and I don't think they automatically display the transcripts for download as in the media players.

@laurensorensen asked about the possibility of doing this today.

We have the .txt files on the servers in `vt/shared/data/fulltext` but not in a public folder.
Not sure if we want to take this on late in the workcycle, or what the UI implications might be, but we do have the files.
If we decide to proceed we should just be mindful of the impacts on the harvesting pipeline and keep track of any changed paths.

**Comment by jcoyne** [comment]
Why would we want to do this?  If someone wants the text, surely they would prefer to get it from stacks where they can do things like exclude introduction pages,etc.

**Comment by marlo-longley** [comment]
That is a question for @laurensorensen -- apparently it was listed as a requirement for the product.

**Comment by ggeisler** [comment]
We heard from potential users that they would really like the full text of all items in the collection so they can do text analysis, etc. It isn't clear that we currently have the necessary legal permission to offer a convenient single download of all collection data, but we were told we can offer the full-text at an item level. 

>  If someone wants the text, surely they would prefer to get the structured OCR from stacks where they can do things like exclude introduction pages,etc.

@jcoyne Do you mean by going to, for example, `https://purl.stanford.edu/ct549bj5123.xml`?

If so, I think the structured data could be useful to the end-user, for sure. On the other hand, the average user is not going to have any idea that they can do that.  So we would need to create a user-friendly affordance (a button or whatever) on the component show page that links to that, and/or to the unstructured .txt file we store in the application.

I think we're just trying to understand what our potential options are so we know whether we should consider adding an affordance for the user to get the full text for an item.

**Comment by jcoyne** [comment]
@ggeisler I'm thinking more of these sorts of files: https://stacks.stanford.edu/file/druid:ct549bj5123/ct549bj5123_0002.xml

**Comment by laurensorensen** [comment]
In my experience working with researchers/ academics who create simple bash or python scripts who aren't devs, they'd prefer working with CSV or plain text and not touching XSLT. Would be great to hear about other experiences if you have examples. 

This is an actual request we got from the Spotlight exhibit in October 2021: 

Dear Sir or Madam, thanks for publishing the documents of the International Court of Justice Archives of the Nuremberg International Military online. But i'm looking for the full/plain text of the digitalized images? i' assistant researcher at the university of wuppertal and i'm looking for material, which i can use for my lecture (python and the humanisits) . Can you provide me a description / How To / Tutorial to get the full/plain/orced text of the digitized documents? Thanks im Advantage, Malte Windrath

**Comment by laurensorensen** [comment]
FWIW, at this stage we don't have permission from ICJ to compile full corpus of OCR plain text. But Tom ok'd the one-at-a-time download of plain text OCR.

**Comment by jcoyne** [comment]
@laurensorensen the files we have created are the full document corpus compiled from distinct pages.  They are not very useful, because we don't have good language detection or even have good script detection for the Cyrillic (or western diacritics).  I given the preponderance of German in the documents, I believe it would be an embarrassment to consider releasing this data and suggesting people use it

**Comment by laurensorensen** [comment]
Good to know, thanks for the examples! Sounds like we'll put it on the long term "must have" instead of short term.

**Comment by marlo-longley** [comment]
@laurensorensen @ggeisler @jcoyne Thank you for the discussion on this. I am thinking we can close this with the conclusion that we will not implement it this workcycle. If there's another path you'd like to take, let me know.
