### ISSUE TITLE
Remove double date from collection title

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#279]
Currently after moving the collection in ASpace and reindexing, we are getting:

### Taube Archive of the International Military Tribunal (IMT) at Nuremberg, 1945-46, 1945-11-20-1946-10-01

Hopefully this is a fix in ASpace, then we can redownload EAD, and reindex.

**Comment by laurensorensen** [comment]
Preferred solution for this would be to suppress the ", 1945-11-20-1946-10-01" appended to the title. The collection level record should have the date associated with it but for whatever reason ASpace is appending it. 

Is the above possible @marlo-longley ? 

If suppressing is not possible, I will delete the date from collection record entirely.

**Comment by laurensorensen** [comment]
FWIW I think general users of ArcLight would prefer to have the date not auto-appended or appended in a manner of their choosing, e.g. 1945-46 or or November 20, 1946 - October 1, 1946  instead of 1945-11-20-1946-10-01.

**Comment by ggeisler** [comment]
I'm really hoping we can stick with `Taube Archive of the International Military Tribunal (IMT) at Nuremberg, 1945-46`

That title is long enough, and is plenty clear. A longer title just makes the UI more cluttered and busy (and makes it more likely the title will wrap a third line in the Collection box, etc.).

**Comment by laurensorensen** [comment]
I removed ", 1945-46" from the end of the title and removed the day/month dates from the date on collection level title. I can't see what happened in the ArcLight view. I guess EAD needs to be re-loaded / refreshed in the API before we can see it in Arclight? @marlo-longley

**Comment by marlo-longley** [comment]
@laurensorensen I re-indexed the latest EAD into my local Arclight and the problem is apparently fixed. Thanks!
