### ISSUE TITLE
Indexing with entire fulltext content errors with timeout out on servers

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#280]
Need to research how to extend the timeout limit, or break this process up.
This is only happening with the addition of all the fulltext files, before that the process did not time out.
This happened on staging but is sure to happen again+ on production...as it stands traject is correctly gathering the fulltext (with the fix included in #281) but fails before it can write into Solr.
I reverted the index on staging to the content inventory without fulltext so that Gary can work.

```sh
...

I, [2022-11-22T14:34:38.883885 #3635727]  INFO -- : traject (3.7.0) executing with: `-u https://sul-solr.stanford.edu/solr/nta-arclight-stage/ -i xml -c lib/traject/vt_config.rb -s repository=icj public/data/mt839rq8746.xml`

...

D, [2022-11-22T14:34:39.437175 #3635727] DEBUG -- : Shutting down #processing mapper threadpool...
D, [2022-11-22T15:07:07.481519 #3635727] DEBUG -- : #processing mapper threadpool shutdown complete.
D, [2022-11-22T15:07:07.482114 #3635727] DEBUG -- : Traject::SolrJsonWriter: Shutting down thread pool, waiting if needed...
D, [2022-11-22T15:07:07.482540 #3635727] DEBUG -- : Traject::SolrJsonWriter: sending batch of 1 to Solr
E, [2022-11-22T15:46:48.919505 #3635727] ERROR -- : Error in Solr batch add. Will retry documents individually at performance penalty:     Exception: HTTPClient::SendTimeoutError: execution expired
    /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/openssl/buffering.rb:358:in `[]='
```

You can see this took an extremely long time, the "Shutting down #processing mapper threadpool..." action took over 30 minutes but did suceed, and the "Traject::SolrJsonWriter: sending batch of 1 to Solr" action took 40 minutes before it timed out and failed.

**Comment by marlo-longley** [comment]
NOTE:
I don't want to mess with staging indexing until Gary is done referencing the staging server before he goes on vacation.

**Comment by jcoyne** [comment]
So much of the fulltext data is junk.  What if we only load the fulltext that is dictionary words? That would significantly reduce the size of the data we're trying to load.

**Comment by marlo-longley** [comment]
That sounds like a fine approach to me, except I would be concerned about throwing out foreign language words. I know we are indexing by English, but it still seemed good to me that someone would be able to search a French or German word, proper noun, etc., with some limited success.

Not sure who should decide this.

**Comment by marlo-longley** [comment]
I am closing this. @cbeer was able to successfully index on vt-stage and vt-prod using the solution of only having a single Solr replica.
