### ISSUE TITLE
Update display of Media format values

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#286]
Maybe this is work planned but I think we've talked about updating a couple of the value for the Media format facet to be different from what I currently see on -stage:

<img width="292" alt="Screen Shot 2022-11-23 at 11 30 33 AM" src="https://user-images.githubusercontent.com/101482/203622074-d75d303f-82d4-4331-8513-27c37c209e8c.png">

- "Graphic Materials" - I suggest using "Image" (singular) as the display value, unless this category includes a significant amount of things that aren't images; "Graphical materials" is a much more ambiguous term than images and I'd expect some users to not understand what is in that category with that label.

- "Moving Images" - lowercase the "I" in "Images". Also, use the singular form ("Moving image") to be consistent with how we display resource format facet values in other applications (Searchworks, Spotlight).

**Comment by jcoyne** [comment]
@ggeisler @laurensorensen  This is the data as it appears in the EAD.

**Comment by laurensorensen** [comment]
@jcoyne Yes the data is that way because we had to use a controlled vocabulary for that field given to us by Spec's ArchivesSpace. They maintain it so we couldn't alter it, and that field has to conform to it.

Is it possible to change the formatting in ArcLight to conform to what Gary outlined?

**Comment by marlo-longley** [comment]
@laurensorensen do our controlled vocabulary restrictions change now that we are no longer using their repository in ArchivesSpace?

**Comment by laurensorensen** [comment]
It does not @marlo-longley. The vocabularies are ASpace system-wide, not based on repository.

**Comment by marlo-longley** [comment]
Gotcha. Thanks!

**Comment by laurensorensen** [comment]
It looks like the plural of "Moving images" was used here instead of singular as indicated in Gary's initial ticket. @jcoyne @marlo-longley

**Comment by marlo-longley** [comment]
@laurensorensen This ticket is closed. I created #364 to track this.
