### ISSUE TITLE
Add fields to component metadata list

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#290]
This ticket supersedes #217, because there is a lot of discussion in that ticket and some aspects are completed, etc.

Key to this ticket is @laurensorensen's [data crosswalk spreadsheet](https://docs.google.com/spreadsheets/d/1a_doAL669TXXzadv3UC07oOAv4jS7cVCsE4wfgqPag0/edit?usp=sharing), which has the details of the mapping to the fields I'm suggesting we display on the component page below.

Below is how an item-level component page might look, if it had all values for all the metadata fields Lauren and I are suggesting we display. (The mockup is not accurate for any specific item.) At higher component levels, such as series and sub-series, we're assuming that most of the fields will not have values, and thus won't be displayed. So, for example, a Series component will have a "Scope and content" value but not much else to display.

<img width="567" alt="Screen Shot 2022-11-23 at 1 07 34 PM" src="https://user-images.githubusercontent.com/101482/203638666-0220ee90-0ea4-49ad-aaea-0d5225fffee1.png">

---

Based on what I see today (2022-11-23), we should:

- Revise the field labels of"Document number" to `Resource identifier`
- Add fields `Date`, `Media type`, `Scope and content`, `Note` (the latter two might be there but just not have values for the items I've checked)
- Reorder fields to match the order in the mockup

The cell values in column E of the [data crosswalk spreadsheet](https://docs.google.com/spreadsheets/d/1a_doAL669TXXzadv3UC07oOAv4jS7cVCsE4wfgqPag0/edit?usp=sharing) correspond to the field labels in the mockup above. So the spreadsheet should help identify which EAD element populates each new field. A couple of other notes:

**A**: If we can link the date value to a search on that date, that would be great. A definite use case is a user being interested in knowing all items in the collection that are associated with a particular date. If we can link this date value, that would help with that.

**B**: Media type, Resource type, Resource format, and Language are all facets, so if we can we should link the values of these fields to a facet search on that value. That would help the user who becomes interested in knowing all the items that have a given facet value.

**Extent**: It looks like we're now displaying something like `1 item(s) and 20 pages` for item-level components, which is fine. My mockup only includes the pages part, but the current approach is okay, especially if it displays something useful at the parent container levels.

**Comment by laurensorensen** [comment]
Please use HH24;MM over AM/PM.

**Comment by laurensorensen** [comment]
Example: 1946-10-04 from 10:00 - 14:10

**Comment by jcoyne** [comment]
> If we can link the date value to a search on that date, that would be great. A definite use case is a user being interested in knowing all items in the collection that are associated with a particular date. If we can link this date value, that would help with that.

We can't do that as the normalized date (`normalized_date_ssm`) is not indexed for search. The normalized date may be a date range with resolution down to 10 minutes. This would make it unlikely that any other document would have the same value.

**Comment by laurensorensen** [comment]
Only audio recordings should have any time information at all associated with them. Does that make a difference on if date is able to be indexed for search? We really need to be able to search and facet by date. I thought that this was possible up until reading this comment... hoping I read your comment wrong! :)

**Comment by jcoyne** [comment]
@laurensorensen Arclight indexes all dates the same way regardless of what granularity they are recorded at or what type of object it is. It does differentiate based on the `unitdate`'s `type` attribute.

**Comment by laurensorensen** [comment]
I don't know if this is helpful or not but I found this in an ASpace API resource. I wonder if the date type could be changed to single where applicable using this? https://archivesspace.github.io/archivesspace/api/#update-an-archival-object 

As @thatbudakguy mentioned in Slack, the uploader spreadsheet forced the use of type "inclusive" even when date was actually "single"

**Comment by laurensorensen** [comment]
Seeing that Document number is listed here but in the crosswalk Gary refers to listing all the field labels (column E), the field label is **Resource identifier**. 

Media type label is also incorrect here: https://github.com/sul-dlss/vt-arclight/issues/343

**Comment by marlo-longley** [comment]
Closing so that we have more discreet issues rather than opening up this one with lots of prior discussion
