### ISSUE TITLE
Seeing 1945-1946 in various places in text, should be 1945-46

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#305]
Taube Archive of the International Military Tribunal (IMT) at Nuremberg, 1945-1946 should be
Taube Archive of the International Military Tribunal (IMT) at Nuremberg, 1945-46

**Comment by marlo-longley** [comment]
@laurensorensen Can you please document where you are seeing this (exactly the page, maybe with a screenshot)?
