### ISSUE TITLE
Need to add a space in between Content Warning and the text of the warning

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#315]
See screenshot 
<img width="500" alt="Screen Shot 2022-11-30 at 3 55 58 PM" src="https://user-images.githubusercontent.com/3269689/204933324-1f43711f-017a-4dfc-9f10-58dfe4e8d944.png">

**Comment by marlo-longley** [comment]
This will be fixed when #314 is merged

**Comment by laurensorensen** [comment]
Appears to be fixed
