### ISSUE TITLE
Display scope + content text 

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#326]
@laurensorensen is currently inputting this into ASpace
We will need to download new EAD and reindex to see it in VT-Arclight, and we can QA from there.

**Comment by marlo-longley** [comment]
Hi @laurensorensen -- can you explain how/why this HTML was generated for the collection-level scope + content, while HTML was not generated for the series level scope + content? If you aren't sure that's fine, I can investigate, but curious if you knew. Obviously the series text is simpler, but still it is not wrapped in any tags.


Colletion level:
![Image](https://user-images.githubusercontent.com/1328900/205307965-c7e79901-8e60-49e7-ab58-f3c91c317105.png)


Series level:


![Image](https://user-images.githubusercontent.com/1328900/205308010-a7fa0d2d-cbc5-40b8-ac0c-f83778367476.png)

**Comment by laurensorensen** [comment]
I added the HTML because it was like that in the original text (links etc), which is what I'm trying to follow as closely as I can. I can strip it if needed... but there is little guidance in ASpace documentation (and none for AL) except what's allowed in EAD and these tags are allowed technically, so I thought I would add and see if the links, list, other html showed up.

**Comment by laurensorensen** [comment]
> We also have problems indexing this new XML containing scope + contents. I would guess this is coming from the collection level text.
> 
> ```
> "responseHeader":{
>     "status":400,
>     "QTime":1852},
>   "error":{
>     "metadata":[
>       "error-class","org.apache.solr.common.SolrException",
>       "root-error-class","java.lang.IllegalArgumentException"],
>     "msg":"Exception writing document id mt839rq8746 to the index; possible analysis error: DocValuesField \"scopecontent_ssm\" is too large, must be <= 32766",
>     "code":400}}
> ```

Ok, looks like it might be too large. I'll try and edit it. Does <= 32766 mean that's the number of characters allowed?

**Comment by marlo-longley** [comment]
@laurensorensen let's hold off on editing until we can dig into how we are formatting the content with or without tags. Removing HTML would remove a significant number of characters. Also, it might be possible to increase that limit.

**Comment by marlo-longley** [comment]
>  added the HTML because it was like that in the original text

Out of curiosity, which original text you're referring to?

**Comment by marlo-longley** [comment]
This indexing issue came up in Arclight Core: https://github.com/projectblacklight/arclight/issues/994

**Comment by marlo-longley** [comment]
@laurensorensen Hi Lauren, not sure what you mean by space for it in Arclight. This data is indexed in our VT staging instance and can be viewed at the collection summary as well as at the series level. Since the data is displayed, I'm closing the issue. If there are specific changes you want to make in QA, let's make detailed tickets for those.
