### ISSUE TITLE
Don't display fulltext search results warning when faceting

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#327]
This warning displayed after interacting with a facet, which makes it seem like the facet data has quality issues:
<img width="1161" alt="Screen Shot 2022-12-01 at 15 19 06" src="https://user-images.githubusercontent.com/1328900/205181551-64516479-b616-47bf-a99b-17c4f0a63039.png">

I realize users can interact with both the search and facets, so I'm not sure if this makes sense, but it's something that felt off. Not super high priority.

**Comment by jcoyne** [comment]
Blacklight doesn't really make a very big distinction between searching and faceting.  What should be the behavior if you have both a text search and a facet selected?  What about if you clicked the search button without entering any text?

**Comment by marlo-longley** [comment]
We can display the alert only if there is a non-empty `q` param in the URL
