### ISSUE TITLE
Explore whether we can add "Staff to Acknowledge" to the site

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#328]
This was requested via CHRIJ via this doc: https://docs.google.com/document/d/1ZbUTyMJ--mHVliU8uScroL2N-oGdvTexNOBoUA8i7lc/edit#heading=h.wajf7ku28h6g

But we do not have designs for it. Thoughts?

**Comment by jcoyne** [comment]
> But we do not have designs for it. Thoughts?

Wait for Gary to return.

**Comment by marlo-longley** [comment]
I'm good with this. I will remove from our 2022 project.

**Comment by marlo-longley** [comment]
Update: This would just be text at the bottom of the /nuremberg page. We are going to check in with stakeholders about whether this is desired/needed.


![Screen Shot 2022-12-02 at 18 13 35](https://user-images.githubusercontent.com/1328900/205404869-d4f4d04d-f836-4d29-95ad-47f8171a445c.png)

**Comment by marlo-longley** [comment]
I'm thinking maybe we should make this an opt-in thing if we go ahead with it. People should actively consent to having their name published.

**Comment by marlo-longley** [comment]
Update: Lauren has asked the CHRIJ folks about this, waiting on a conclusion.

**Comment by laurensorensen** [comment]
Checked back with Penelope and she's good with the group acknowledgments. We can get @ggeisler 's feedback too when he's back. I'll create some copy on this, hopefully will post here by end of the day.

**Comment by laurensorensen** [comment]
Draft for Stanford staff acknowledgements: 

We are grateful for the collaboration of our Stanford University colleagues for all the work and effort put into the Nuremberg Trial Archives project and site. In particular, we wish to thank our collaborators from the Center for Human Rights & International Justice for leadership, curatorial and subject specialist expertise, Stanford University Libraries' (SUL) Special Collections staff for their assistance utilizing ArchivesSpace, SUL Bibliographers for curatorial support and outreach, SUL Media Preservation Lab for their assistance with accessioning, captioning and transcripts, and Digital Library Systems & Services (DLSS) Access & Discovery team for building out the site’s technical capability, including extensive data work and design, the DLSS Product & Service Management team for numerous points of support and assistance, the DLSS Operations team for ongoing site maintenance and help with back-end, server-side issues.

**Comment by marlo-longley** [comment]
Hi @laurensorensen -- you say this is a draft. Let me know when you consider to final. Then I will add the text. Thanks!

**Comment by laurensorensen** [comment]
Thanks @marlo-longley - here is the final version: 

We are grateful for the collaboration of our Stanford University colleagues for the work and effort put into the Nuremberg Trial Archives project and site. In particular, we wish to thank our collaborators from the Center for Human Rights & International Justice for leadership, curatorial and subject specialist expertise, Stanford Libraries' Special Collections staff for their assistance utilizing ArchivesSpace, bibliographers for curatorial support and outreach, Stanford Media Preservation Lab for their assistance with accessioning, captioning and transcripts, and Digital Library Systems & Services (DLSS) Access & Discovery team for building out the site’s technical capability, including extensive data work and design, the DLSS Product & Service Management team for numerous points of support and assistance, and the DLSS Operations team for ongoing site maintenance and help with back-end, server-side issues.

--

And as you suggested before, let's take out Dinah's name from the Acknowledgments section and keep "community manager"
