### ISSUE TITLE
Rights statement not appearing in collection record view in Arclight 

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#329]
Right now, the Rights statement data exists in ArchivesSpace collection level record but does not display in Arclight. This would be a desirable feature for other Arclight users if not already an option.

**Comment by marlo-longley** [comment]
Hi @laurensorensen, could you add a screenshot of where you'd like this to display?

**Comment by marlo-longley** [comment]
Hi @laurensorensen -- I discovered that this data is not coming through in the EAD.
I found [this discussion:](http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2019-May/006776.html)

> 
Unfortunately that's right.  The rights statement records (as well as some other record types, like event records) do not appear in the public interface as far as I'm aware.  They also do not get added to EAD exports (although they could, if there were a mapping for that data).

We will need to provide this data in the app directly, similar to how we entered the landing page text.

**Comment by marlo-longley** [comment]
We could add this to the `repositories.yml` file and then do [something similar to the way we handle the location data](https://github.com/sul-dlss/vt-arclight/blob/c14d8b26c9b463d2c2a32c8cd529319a01239ab1/app/controllers/catalog_controller.rb
).

**Comment by marlo-longley** [comment]
Hey @laurensorensen -- I was just providing that as a possible implementation route. We will have to dig into it to find the best solution. But yes the location, digital stewardship info, etc, comes from that file.

**Comment by laurensorensen** [comment]
Ok, let me know if you want to chat further or if I can help in any way

**Comment by marlo-longley** [comment]
I want to make this change in Production ASpace, and pull the data from there, ASAP, but work is ongoing in #339

**Comment by laurensorensen** [comment]
Ok, I added the text to this in spec-as-prod
