### ISSUE TITLE
Date facet not ordered by year, order seems to be by number of items 

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#331]
<img width="384" alt="Screen Shot 2022-12-01 at 6 55 46 PM" src="https://user-images.githubusercontent.com/3269689/205204759-edb029ee-05fd-4036-92f9-ed7b571f4f00.png">

**Comment by marlo-longley** [comment]
Will we be keeping the Year facet after implementing the hierarchical date facet? I thought it would be replaced. Good to clarify either way.

**Comment by jcoyne** [comment]
> Date facet not ordered by year, order seems to be by number of items 

@laurensorensen yes, this is true.  Should it be otherwise?

**Comment by marlo-longley** [comment]
Overridden by #184
