### ISSUE TITLE
Title font should be smaller, so the full text can be on one line 

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#332]
<img width="1065" alt="Screen Shot 2022-12-01 at 7 02 50 PM" src="https://user-images.githubusercontent.com/3269689/205205688-5df4942c-7730-417d-a657-196ed889db15.png">

I think Gary mentioned dealing with this when he's back.

**Comment by marlo-longley** [comment]
Hey @laurensorensen -- are you saying you'd like to consider this issue out of scope for this workcycle (if you want to wait until Jan.?)

**Comment by jcoyne** [comment]
I think this existing PR is going to affect this: https://github.com/sul-dlss/vt-arclight/pull/309

**Comment by laurensorensen** [comment]
> Hey @laurensorensen -- are you saying you'd like to consider this issue out of scope for this workcycle (if you want to wait until Jan.?)

@marlo-longley  That's fine - but it seems like it's been fixed now that the title is centered. Seems best to have Gary review it, though.
