### ISSUE TITLE
Load a sampling of useful documents in the solr:seed task

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/vt-arclight#335]
The task is currently a no-op:

```
namespace :solr do
  task seed: :environment do
    # TODO: load some docs here
  end
end
```

I think we should load a subset of the whole data for ease of development, and so we can write some meaningful integration tests.

**Comment by jcoyne** [comment]
I believe @marlo-longley has an abridged EAD for this sort of thing.

**Comment by marlo-longley** [comment]
I do. I need to spend some time refining it to reflect the current state of the data, and give a good sampling of most of types of our data. I can assign myself this ticket.

**Comment by marlo-longley** [comment]
Sample EAD criteria coming out of group discussion:

- One of every date, type, etc
- Nick’s Georing idea for relevancy
- No super graphic content
- One of each language
- Include Bandera for transliteration
