### ISSUE TITLE
Handle year-only dates in hierarchical date facet

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/vt-arclight#337]
With the implementation in #191, indexing using the latest EAD will throw `Date::Error`s when trying to parse our single-year ranges (output shown is from logging them):
```
W, [2022-12-02T10:36:57.518622 #11185]  WARN -- : Date parse error: 1936/1936
W, [2022-12-02T10:37:01.172828 #11185]  WARN -- : Date parse error: 1899/1899
W, [2022-12-02T10:37:01.189159 #11185]  WARN -- : Date parse error: 1907/1907
W, [2022-12-02T10:37:11.890082 #11185]  WARN -- : Date parse error: 1943/1943
W, [2022-12-02T10:37:11.905433 #11185]  WARN -- : Date parse error: 1942/1942
W, [2022-12-02T10:37:12.080363 #11185]  WARN -- : Date parse error: 1942/1942
W, [2022-12-02T10:37:38.943727 #11185]  WARN -- : Date parse error: 1943/1943
```
The counts are also confusing — the year-span items appear to count as being on every month (and day) of their year.

![Screen Shot 2022-12-02 at 10 45 15](https://user-images.githubusercontent.com/4924494/205364105-09351bcb-1a72-4fa4-a539-3345d7c52f1c.png)

We might need to do some thinking about how to correctly index these dates.

**Comment by marlo-longley** [comment]
We can't reindex until this is resolved.
