### ISSUE TITLE
Upload final data into production ASpace

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#338]

**Comment by marlo-longley** [comment]
It's important that the HTML is copied directly from the staging ASpace interface because I made some fixes to the HTML there, which won't be reflected in the original source or file.

**Comment by laurensorensen** [comment]
@thatbudakguy @marlo-longley I added a comment here that maybe I should have added to this ticket. Could I "by hand" add a few fields of info to the film records before this is finalized? I would do that within ASpace, would take me probably 10-15 mins. It's these descriptions/categories of the films, I think will help people identify with better clarity than just the titles... https://github.com/sul-dlss/vt-arclight/issues/339#issuecomment-1340149810

**Comment by thatbudakguy** [comment]
data has been uploaded to production.
