### ISSUE TITLE
Change Document number to Resource identifier in component metadata label

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#346]
Seeing that Document number is listed here but in the [crosswalk Gary refers to listing all the field labels ](https://docs.google.com/spreadsheets/d/1a_doAL669TXXzadv3UC07oOAv4jS7cVCsE4wfgqPag0/edit#gid=947649582)(column E), the field label is **Resource identifier**. 
<img width="912" alt="Screen Shot 2022-12-02 at 5 43 44 PM" src="https://user-images.githubusercontent.com/3269689/205416695-4e8786c6-009f-4be7-86e7-7463b0f2e1c4.png">

_Originally posted by @laurensorensen in https://github.com/sul-dlss/vt-arclight/issues/290#issuecomment-1336006691_

**Comment by jcoyne** [comment]
@laurensorensen @marlo-longley  Just giving a heads up that "Document number" is used in the descriptive metadata, so you may want to search for that an change it.:
```xml
              <dao xlink:actuate="onRequest" xlink:audience="external" xlink:href="https://purl.stanford.edu/tn371bv5392" xlink:show="new" xlink:title="Cross-index of PS, C, D, EC, ECH, F, L, M, R, TC, UK Documents (by Document number)" xlink:type="simple">
                <daodesc>
                  <p>Cross-index of PS, C, D, EC, ECH, F, L, M, R, TC, UK Documents (by Document number)</p>
                </daodesc>
              </dao>
```
