### ISSUE TITLE
Date facet not showing up on Search page

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#354]
Example search page (after having entered the search from main page, clicked eyeglass icon. This page shows up with facets on the side, but no date facet is presented. https://virtualtribunals-stage.stanford.edu/nuremberg?search_field=all_fields&q=1936-1940

<img width="802" alt="Screen Shot 2022-12-05 at 4 18 46 PM" src="https://user-images.githubusercontent.com/3269689/205775054-07149898-905a-41bc-871e-558caf472f74.png">

**Comment by jcoyne** [comment]
This is the expected behavior because the two documents in the result set do not have any values in the date facet (`date_hierarchy_ssim`).

**Comment by laurensorensen** [comment]
Closing per @jcoyne's comment above
