### ISSUE TITLE
Searching "Göring" should return 194 results

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#357]
We saw that "Göring" (with umlaut) was a top search in the Spotlight VT exhibit. 
Currently searching with that character returns 1 result (the top-level collection, which includes his name in its scope and contents text, and therefore came directly from Lauren typing it into ASpace).

Searching "Goering" returns the correct 194 number of results. We want "Göring" to return the same number.

**Comment by jcoyne** [comment]
This may be fixed after #362 because it moves fields to be text based. Text fields use the ICUFoldingFilterFactory, which removes the diacritics.

**Comment by jcoyne** [comment]
@marlo-longley I'm not able to duplicate your first result. I see 1 result for either search:

https://virtualtribunals-stage.stanford.edu/nuremberg?search_field=all_fields&q=Goring
<img width="1156" alt="Screenshot 2022-12-08 at 11 51 42 AM" src="https://user-images.githubusercontent.com/92044/206526890-7113442c-b29d-43cd-96d9-ac34d85ec6d4.png">

https://virtualtribunals-stage.stanford.edu/nuremberg?search_field=all_fields&q=G%C3%B6ring
<img width="1028" alt="Screenshot 2022-12-08 at 11 52 20 AM" src="https://user-images.githubusercontent.com/92044/206527062-048f95df-1261-4efd-9bbf-b819fa375908.png">

**Comment by jcoyne** [comment]
Oh, you are are searching for "G*oe*ring"

**Comment by marlo-longley** [comment]
Now that we've indexed the fulltext, we have more than 194 results. However, the mapping of Göring to results containing Goering is working properly. 



![Image](https://user-images.githubusercontent.com/1328900/207710107-77261141-0334-4481-86e1-fb793db9af63.png)
