### ISSUE TITLE
Document how staging and production ASpace should be used

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#359]

**Comment by marlo-longley** [comment]
@thatbudakguy currently we have this set in vault/puppet for the staging server:  `ASPACE_URL=http://spec-as-stage.stanford.edu:8089`. It is set to `spec-as-prod` for the production server.

I'm gathering we should set the VT staging server to point to production ASpace as well. But wanted to bounce that off someone.

**Comment by thatbudakguy** [comment]
Yes, I think we should set the staging server to have `ASPACE_URL=http://spec-as-prod.stanford.edu:8089`.

If you ever want to generate some EAD out of staging instead of production, that should be an operation where you manually specify `ASPACE_URL`. The default should always be prod.
