### ISSUE TITLE
Should the transcripts for 36 videos be indexed for fulltext search?

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#363]
Currently they will not be.
E.g. https://argo.stanford.edu/view/xc899yd7022
They do not have `Role=Transcription` set as do the OCR transcripts we otherwise are harvesting.

**Comment by marlo-longley** [comment]
Andrew confirms, that yes, they are doing this wrong intentionally because the viewer won’t support the right way.

**Comment by laurensorensen** [comment]
I think indexing of the video transcripts should be done at some point, but it's ok if this can't be made a priority for this final sprint.

**Comment by jcoyne** [comment]
If we want to index these please add the "role=transcription" to the description of the resources via Argo.  Then we can update the harvester to pull these transcripts down.  We'll have to differentiate between ALTO XML transcripts and text/plain transcripts.

**Comment by laurensorensen** [comment]
Ok, the above is done now, in Argo @jcoyne

**Comment by marlo-longley** [comment]
Thanks @laurensorensen  -- I'm seeing in the example Argo link above that both the .txt transcript files, and the .vtt caption files, now have `Role=Transcription` -- is this correct? Would the content of the .vtt English captions duplication the .txt English transcript as far as indexing is concerned?

**Comment by laurensorensen** [comment]
@marlo-longley yes the vtt would be repeating text of what is in the .txt files.

I had thought I only added role to the plain text files (I saw text/plain when I downloaded the structural metadata). The vtt files aren't available or set for download, don't know if that matters here. 
<img width="312" alt="Screen Shot 2022-12-07 at 9 41 09 AM" src="https://user-images.githubusercontent.com/3269689/206253748-3373821a-d006-449c-9f60-44e69981660b.png">

**Comment by marlo-longley** [comment]
Hey @laurensorensen -- The .vtt files could be read the by harvester event though they aren't available in the viewer for download. But they now have Role=Transcription:

<img width="1312" alt="Screen Shot 2022-12-07 at 13 05 15" src="https://user-images.githubusercontent.com/1328900/206261381-458e567e-6739-4cf7-813b-f28a6881395f.png">
