### ISSUE TITLE
Minor HTML link error in scope and content for collection

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#365]
IMT Charter's link is in the wrong spot. See screenshot

<img width="722" alt="Screen Shot 2022-12-06 at 3 24 20 PM" src="https://user-images.githubusercontent.com/3269689/206047059-28dcb857-3149-4798-8aaa-170f4d9554ff.png">

**Comment by jcoyne** [comment]
This appears to be as we see it in the EAD:
```xml
 <title>International Military Tribunal (IMT) Crimes</title>
<p>
Article 6 of the IMT's Charter listed three broad categories of crimes:
</p>
   <a href="https://treaties.un.org/pages/showDetails.aspx?objid=08000002801572a2">IMT's Charter</a>
     <p>
a) Crimes against peace: namely, planning, preparation, initiation or waging of a war of aggression, or a war in violation of international treaties, agreements or assurances, or participation in a common plan or conspiracy for the accomplishment of any of the foregoing;<br/>
```

**Comment by marlo-longley** [comment]
Happy to make the edit in ASpace @laurensorensen ; just let me know where you'd like the link to be placed instead.

**Comment by thatbudakguy** [comment]
@marlo-longley let's make this change in production ASpace, since the data is now there

**Comment by marlo-longley** [comment]
Awesome. Yes let's link up about making that shift to production and communicating that we should do future editing in production.

**Comment by laurensorensen** [comment]
Done
