### ISSUE TITLE
Spelling of Göring's name should be consistent in scope and content of collection record

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#366]
See screenshot, two different spellings. Prefer:  Hermann Göring as it is on the USHMM encyclopedia. 

<img width="632" alt="Screen Shot 2022-12-06 at 3 50 59 PM" src="https://user-images.githubusercontent.com/3269689/206051019-e4beda4f-1463-416e-a7be-17307e23f478.png">

**Comment by marlo-longley** [comment]
@jcoyne correct. I just made the edit. This will be reflected next time we download and index new EAD.
