### ISSUE TITLE
Add a few fields to ASpace production for film

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#368]
Column M in "USHMM collection name" should be added to Scope and content for film items only
@laurensorensen will complete
https://docs.google.com/spreadsheets/d/1QGcCtrGgASdvU6cHG7t09UVXMAk_DIN110zuWv42914/edit#gid=1206926021

**Comment by laurensorensen** [comment]
This is done, except for Hannah is going to review to review my "by hand" data entry this afternoon

**Comment by marlo-longley** [comment]
Awesome! Does the same apply to #339  ?

**Comment by laurensorensen** [comment]
Ok, Hannah's reviewed and it's all set including the text for the Collection record that was to be entered by-hand.

**Comment by laurensorensen** [comment]
> Awesome! Does the same apply to #339 ?

Yes, all done
