### ISSUE TITLE
Change mime type of VTT files to text/vtt

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#369]
This is in the SDR metadata for videos.

**Comment by laurensorensen** [comment]
This is done

**Comment by marlo-longley** [comment]
@laurensorensen I think we were hoping to change text/plain to text/vtt. Is that possible?

**Comment by laurensorensen** [comment]
Ah shoot, OK - I think I misheard this morning. I will change text/plain to text/vtt. Will comment here when it's done

**Comment by laurensorensen** [comment]
@jcoyne Do I need to put back role=transcription to the fields where text/vtt is indicated?

**Comment by jcoyne** [comment]
> Do I need to put back role=transcription to the fields where text/vtt is indicated?

No, VTTs are a kind of transcript, so I think that role is appropriate.

**Comment by marlo-longley** [comment]
Just to clarify, @laurensorensen removed the Role=Transcription. So she would need to add them back in this case. Wondering if that is necessary.

**Comment by jcoyne** [comment]
As long as the mime-type is correctly set to text/vtt, the role doesn't matter.
