### ISSUE TITLE
Media type not showing up in sidebar facets

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#378]
<img width="407" alt="Screen Shot 2022-12-07 at 4 26 21 PM" src="https://user-images.githubusercontent.com/3269689/206326369-e400e921-b76a-4f25-a62a-3127c0dbb2db.png">

**Comment by jcoyne** [comment]
I believe this is expected as we are waiting for this change to be deployed and the entire site to be reindexed: https://github.com/sul-dlss/sul-solr-configs/pull/248

**Comment by jcoyne** [comment]
It's now displaying on stage after a deploy and reindex.
<img width="343" alt="Screenshot 2022-12-08 at 8 50 39 AM" src="https://user-images.githubusercontent.com/92044/206477614-72a2e43c-289d-4796-9acd-8a002198d694.png">
