### ISSUE TITLE
Add DevOpsDocs

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#397]
include info on Solr replicas, and the SLA

**Comment by marlo-longley** [comment]
Addressed in https://github.com/sul-dlss/DevOpsDocs/pull/623/files

**Comment by marlo-longley** [comment]
Edits need to be made in this file: https://github.com/sul-dlss/DevOpsDocs/blob/master/projects/virtual-tribunals/checklist.md

- high SLA
- delete code coverage by tests via [Coveralls](https://coveralls.io/repos/new)
- remove shared configs bc we use Vault
- add vault to template
- remove  document regularly scheduled maintenance windows for the application / dependencies (we do mondays)
- talk to Ops about determine log retention policy and make it so. -- Cloudwatch? can combine two sets of logs. do they rotate logs? monitor disc space?
- mailing list item ?? Should @laurensorensen create a list? ATeam + Lauren, maybe Hannah.
- long term user advocate (replace_with_sunetid) -- remove or add Lauren
- Open PR for the Puppet Facts section in Puppet
- Nagios section can be checked off when https://github.com/sul-dlss/operations-tasks/issues/3250 is closed
-

**Comment by laurensorensen** [comment]
Mailing list created: https://mailman.stanford.edu/mailman/listinfo/virtualtribunals-maintainers

**Comment by marlo-longley** [comment]
The SLA is not reflected here in puppet: https://github.com/sul-dlss/puppet/blob/0c5fe8b9426c5f7f906898c150f41508fa237d56/hieradata/node/vt-prod-a.stanford.edu.eyaml#L15

**Comment by thatbudakguy** [comment]
re:
> talk to Ops about determine log retention policy and make it so. -- Cloudwatch? can combine two sets of logs. do they rotate logs? monitor disc space?

digging around in puppet suggests that log rotation is handled for us in most cases:

https://github.com/sul-dlss/puppet/blob/d16403e8574a4e12cb7bdd0bd8c311d036a47c28/modules/profile/manifests/logrotate.pp#L5-L7

**Comment by marlo-longley** [comment]
Closing https://github.com/sul-dlss/DevOpsDocs/pull/637
