### ISSUE TITLE
Decide on process of moving ASpace records from staging to production

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#40]
Once we have final data formatted in staging ASpace, we will need to ask Michael Olsen to migrate it into production. He indicated the process was to request him.
We will also want to request a set of credentials that our app can use in production to connect to the API.
For production app creds should we only need the following permission level
`view_repository`

**Comment by marlo-longley** [comment]
Update: getting different info from Michael now. He is not sure of the migration process and may need dev support.

**Comment by marlo-longley** [comment]
We agree that our prod app will pull from prod ASpace server

**Comment by marlo-longley** [comment]
Michael Olsen says he will let me know this week whether he has a pathway for promoting data from ASpace staging to production, or if we will need to directly upload our data into production.

**Comment by thatbudakguy** [comment]
That guide seems like it has 20+ manual steps of editing EAD, which is not ideal. I think just reuploading the current data to prod is fine. In the future we should make sure that curators or whoever edits data in prod only, and we may need to figure out a better way to small chunks of data from prod into stage, but for now it should be OK.

**Comment by marlo-longley** [comment]
@thatbudakguy I agree.

I wonder though whether this will create a lot of extra work for @laurensorensen who is inputting scope and contents text currently to staging. To your point about future work being done in production..

**Comment by marlo-longley** [comment]
We don't think manual entry in production will be too hard. Closing as decision is made.
