### ISSUE TITLE
Load test Wowza server

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#400]
We think we can send requests to https://sul-wowza-stage.stanford.edu/ with endpoints similar to:

```
https://sul-mediaserver.stanford.edu/stacks/_definst_/sd/545/hp/5163/mp4:sd545hp5163_FV4303_v4_sl.mp4/media_w212436959_7.ts?stacks_token=<token>
```

The number before .ts in this endpoint increments by 1 for each 5MB chunk in the video, e.g. media_w212436959_1, media_w212436959_2, etc.

**Comment by marlo-longley** [comment]
@jcoyne not exactly sure good to get a valid token. If you inspect a request coming from sul-embed, like on one of the videos from NTA, you'll see a token attached and likely could copy that? Otherwise not sure.

**Comment by jcoyne** [comment]
If I'm reading this right, tokens are only valid for 5 seconds: https://github.com/sul-dlss/shared_configs/blob/sul-stacks-stage/config/settings/production.yml#L11

**Comment by marlo-longley** [comment]
@jcoyne hm yes, it does seem like 5 seconds. But above that same line is there a clue about a potentially more useful endpoint for testing? `https://sul-wowza-stage.stanford.edu/stacks_test/_definst_` ? Or is that a totally fake URL? I can't tell.

**Comment by marlo-longley** [comment]
We would have to pull code out of stacks to generate the tokens; basically writing a whole program
We'd have to figure out how to generate the chunked playlist, ideally with random video so we don't hit caches.

**Comment by jcoyne** [comment]
>  But above that same line is there a clue about a potentially more useful endpoint for testing? https://sul-wowza-stage.stanford.edu/stacks_test/_definst_ ? Or is that a totally fake URL? I can't tell.

I have no idea what that is for. As far as I can tell, that url is never used by stacks.

**Comment by thatbudakguy** [comment]
@marlo-longley can we close this as wontfix? I think we determined there's no way we can do it.

**Comment by marlo-longley** [comment]
@thatbudakguy yes. Essentially we concluded as a team that this is too complex to test.
