### ISSUE TITLE
Load test application, including searches

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#401]
Based on analytics we see that ~15% of sessions include searches / Solr requests.
Some analysis of numbers here: https://docs.google.com/document/d/10zrHQDsUn40NpTfPxKj6Fauf3Z1_jNd1wnqQvmtFGiE/edit

Test scenarios we'd like to pass:

1. **Landing page views:** 400 pageviews/minute traffic to /nuremberg. This is double the approximate peak from the Spotlight exhibit. (@jcoyne did some preliminary testing that indicated 600/s was the failure point)

3. **Searches hitting Solr:** Using the same of peak Spotlight numbers, and doubling again, we get 520 sessions with search per hour. However, one session probably performed many searches within that hour, and I don't believe have any data on that. If each session only performed 1 search, we'd have 8 searches / minute. I don't know what a good number would be on top of 8, to account for the multiple searches per session.

Open to input on these very rough numbers, and other scenarios.

Note, I created a separate ticket for load testing the media server #400

**Comment by jcoyne** [comment]
> @jcoyne did some preliminary testing that indicated 600/s was the failure point)

No, I said it could support 600 req/s with no problems

**Comment by marlo-longley** [comment]
Gotcha thanks for clarifying

**Comment by marlo-longley** [comment]
Update: Marlo will document decision not to test Wowza, and that the test described above covers our bases.

**Comment by marlo-longley** [comment]
#400 is closed as wontfix. We can close this as well.
