### ISSUE TITLE
Reindex stage and prod

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#408]
Can do via API (but update this to reflect new IDs, and production)

`
curl -H "X-ArchivesSpace-Session: f3f59c63689e28ab346af9fee0fa7e7d65df4b30c20c09340cc93360cc18cc9b" -X POST "http://spec-as-stage.stanford.edu:8089/repositories/18/resources/10213/publish"`

**Comment by thatbudakguy** [comment]
iirc there's an ASpace setting (that is per-repository) that you can change so that things will default to published; I forget whether we did this in stage but I'm guessing it's off for production. we might want to change that going forward in case it becomes relevant again.

**Comment by marlo-longley** [comment]
Hey @thatbudakguy it seems this is already set, but didnt have the effect? Is this what you were referring to?

<img width="716" alt="Screen Shot 2022-12-16 at 15 27 05" src="https://user-images.githubusercontent.com/1328900/208183653-5cd832a5-5ac4-4e52-b953-e7dbb2704c7a.png">

**Comment by marlo-longley** [comment]
Update: I ran the publish all script.

**Comment by thatbudakguy** [comment]
Hmm yeah, that's what I was thinking of. Guess it didn't do what I thought!

**Comment by marlo-longley** [comment]
Let's wait to reindex until https://github.com/sul-dlss/vt-arclight/issues/413 is also complete.
