### ISSUE TITLE
Acknowledgments edits

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#411]
I wasn't clear in the last ticket that a separate paragraph should be added after the first paragraph that was already there for Acknowledgments. We have to have a section that thanks Taube and ICJ specifically. This is what the text should look like under the Acknowledgments header: 

We are grateful for the collaboration of the [International Court of Justice, Library of the Court](https://www.icj-cij.org/en/library) [Taube Philanthropies](https://www.taubephilanthropies.org/) for the generous gift that made this project possible. We are also grateful for the involvement of the wider [ArcLight](https://library.stanford.edu/projects/arclight) open-source community for their efforts during this development process and subsequent collection site release. Additionally, we would like to thank the [United States Holocaust Memorial Museum (USHMM)](https://www.ushmm.org/) who shared the results of their cataloging efforts, a portion of which is included. 

We also wish to thank our Stanford University colleagues for the work and effort put into the Nuremberg Trial Archives project and site. In particular, we wish to thank our collaborators from the Center for Human Rights & International Justice for leadership, curatorial and subject specialist expertise, Stanford Libraries' Special Collections staff for their assistance utilizing ArchivesSpace, bibliographers for curatorial support and outreach, Stanford Media Preservation Lab for their assistance with accessioning, captioning and transcripts, and Digital Library Systems & Services (DLSS) Access & Discovery team for building out the site’s technical capability, including extensive data work and design, the DLSS Product & Service Management team for numerous points of support and assistance, and the DLSS Operations team for ongoing site maintenance and help with back-end, server-side issues.

**Comment by laurensorensen** [comment]
@marlo-longley I am so sorry - getting fatigued and didn't double check this. Here is the final copy: 

We are grateful for the collaboration of the [International Court of Justice, Library of the Court](https://www.icj-cij.org/en/library) and the [Taube Philanthropies](https://www.taubephilanthropies.org/) for the generous gift that made this project possible. We are also grateful for the involvement of the wider [ArcLight](https://library.stanford.edu/projects/arclight) open-source community for their efforts during this development process and subsequent collection site release. Additionally, we would like to thank the [United States Holocaust Memorial Museum (USHMM)](https://www.ushmm.org/) who shared the results of their cataloging efforts, a portion of which is included.

We also wish to thank our Stanford University colleagues for the work and effort put into the Nuremberg Trial Archives project and site. In particular, we want to thank our collaborators from the Center for Human Rights & International Justice for leadership, curatorial and subject specialist expertise, Stanford Libraries' Special Collections staff for their assistance utilizing ArchivesSpace, bibliographers for curatorial support and outreach, Stanford Media Preservation Lab for their assistance with accessioning, captioning and transcripts, and Digital Library Systems & Services (DLSS) Access & Discovery team for building out the site’s technical capability, including extensive data work and design, the DLSS Product & Service Management team for numerous points of support and assistance, and the DLSS Operations team for ongoing site maintenance and help with back-end, server-side issues.

**Comment by marlo-longley** [comment]
Gotcha. Thanks!
