### ISSUE TITLE
text change in message shown upon searching text

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#412]
Suggestion by Tom in the demo from 12/15/2022: remove reference to "quality of the scans" and instead refer to OCR. 

Suggest this draft text:
"Your query was matched to the scanned text of all text documents in the collection. Due to the potential for poor quality during the Optical Character Recognition (OCR) process, these search results may include incorrect matches."

<img width="1102" alt="Screen Shot 2022-12-15 at 4 18 35 PM" src="https://user-images.githubusercontent.com/3269689/207993895-5860e729-9f45-4e59-9742-5e25f72bbe89.png">

**Comment by thatbudakguy** [comment]
this text is now deployed, so closing — we can reopen or make a new ticket if we revisit the language
