### ISSUE TITLE
Message that ICJ wants to replace one document (H-0000) and include a new one (H-2785)

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#413]
I can do the accessioning and enter by hand to ArchivesSpace, but I think this would include further work with exporting a new EAD record and then indexing again..? If I am understand correctly @marlo-longley.  Just got word about this today. 

From Tom's email: "ICJ is adding a document to the corpus — this will be H-2785. We need to include this in the site. We also need to swap out the inventory files - H-0000 - with the new replacement referenced below, in order to have the updated inventory."

ICJ doesn't expect any further changes.

**Comment by marlo-longley** [comment]
Hi @laurensorensen  -- yes please go ahead and edit this in Production ASpace. Then we can check in about reindexing.

**Comment by laurensorensen** [comment]
There are issues happening with Goobi that is making it so we have to leave this for the new year re: accessioning the two replacement files. 

Another update is that we need to add this one record to the data pipeline. The data is committed to this repo, making it so @marlo-longley or another dev with write access should make the commit. 

Attached the Excel sheet with the data here: https://docs.google.com/spreadsheets/d/1nR96BxdQpxa92Lmi7BRs3E72GzGXnIp2/edit?usp=share_link&ouid=116571178623773097335&rtpof=true&sd=true

**Comment by marlo-longley** [comment]
https://github.com/sul-dlss/sul-goobi/issues/322 is the accessioning ticket

**Comment by laurensorensen** [comment]
> Hi @laurensorensen -- yes please go ahead and edit this in Production ASpace. Then we can check in about reindexing.

This has been completed: http://spec-as-prod.stanford.edu:8080/resources/12496/edit#tree::archival_object_1273135

**Comment by laurensorensen** [comment]
> > Hi @laurensorensen -- yes please go ahead and edit this in Production ASpace. Then we can check in about reindexing.
> 
> This has been completed: http://spec-as-prod.stanford.edu:8080/resources/12496/edit#tree::archival_object_1273135

Just wanted to note that even though this is done, the PURL / druid for H-0000 won't be confirmed until 2023, so digital record attached to this resource record in ASpace may not be 100% accurate. In case that helps you all decide want to index before or after break.

**Comment by marlo-longley** [comment]
Closing in favor of #431
