### ISSUE TITLE
Is it expected that Goering, Goring, and Göring return different numbers of results in search?

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#414]
<img width="665" alt="Screen Shot 2022-12-16 at 12 48 17" src="https://user-images.githubusercontent.com/1328900/208158302-c0c97ea6-aad9-40ad-8f21-aef60b21a61e.png">
<img width="682" alt="Screen Shot 2022-12-16 at 12 48 24" src="https://user-images.githubusercontent.com/1328900/208158305-657bda35-8a01-46fe-b5b4-5ef03e15c5ec.png">
<img width="591" alt="Screen Shot 2022-12-16 at 12 48 30" src="https://user-images.githubusercontent.com/1328900/208158306-60506590-5096-4da9-8086-ccd4699e25b8.png">

**Comment by jcoyne** [comment]
Most likely. The SynonymFilterFactory only operates on the text_en type (`*_te*`) fields. Any fields that are strings (`*_s*`) don't have synonyms.  We are quering on these fields: https://github.com/sul-dlss/vt-arclight/blob/main/solr/conf/solrconfig.xml#L88-L99  You can do a search in solr with the debug field passed and it will show you how it makes matches.
