### ISSUE TITLE
Minor text edit on landing page 

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#419]
_Access and preservation of the archive of the Nuremberg Trial Archives is made possible due to the generous support of the [Taube Philanthropies](https://www.taubephilanthropies.org/)._ 

Should instead be: 
_Access and preservation of the Nuremberg Trial Archives is made possible due to the generous support of [Taube Philanthropies](https://www.taubephilanthropies.org/)._

**Comment by laurensorensen** [comment]
Here are the links where this should be changed (can do a find in the page to locate):
https://virtualtribunals-stage.stanford.edu/

https://virtualtribunals-stage.stanford.edu/nuremberg

**Comment by marlo-longley** [comment]
@laurensorensen this seems to conflict with this ticket https://github.com/sul-dlss/vt-arclight/issues/416

Now this text is only present once, on the page https://virtualtribunals-stage.stanford.edu/ -- correct?

**Comment by laurensorensen** [comment]
This is to change the text itself, there is a repeat of the word "archive" - what is bold below should be removed @marlo-longley 

Access and preservation **of the archive** of the Nuremberg Trial Archives is made possible due to the generous support of the [Taube Philanthropies](https://www.taubephilanthropies.org/).

Should instead be:
Access and preservation of the Nuremberg Trial Archives is made possible due to the generous support of [Taube Philanthropies](https://www.taubephilanthropies.org/).

**Comment by laurensorensen** [comment]
Sorry, yes it conflicts. Removing entirely the text from Taube page is what we should do. Thanks for catching that. @marlo-longley
