### ISSUE TITLE
Update H-0000 and H-2785 metadata 

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#431]
Previous ticket: https://github.com/sul-dlss/vt-arclight/issues/413

H-0000 is in the process of being accessioned, there was an issue with Goobi, so we're waiting on this to be resolved: https://github.com/sul-dlss/sul-goobi/issues/322

Once the accessioning happens, the metadata will need to be replaced in the items_only and regenerate the data -- as well as add in ASpace production. 

ASpace production records H-0000 and H-2785 is almost all the way updated except for the question on if the druid will stay the same which effects the "digital object" in ASpace, so the Goobi bug/ticket potentially blocks indexing as well.

**Comment by marlo-longley** [comment]
Blocked by outside team process / Goobi
We will reindex once this is done

**Comment by laurensorensen** [comment]
Goobi process proceeded here and was fixed! The druid is the same as before: https://argo.stanford.edu/view/druid:hj785rz1466

**Comment by marlo-longley** [comment]
thanks @laurensorensen ! I see your link is for H-0000. What is the status of H-2785?

**Comment by laurensorensen** [comment]
Sure thing. H-2785 is all set as of before break. The block was the possibility that we would have to change the H-0000 druid only. I've added H-2785 to ArchivesSpace with its associated druid: http://spec-as-prod.stanford.edu:8080/resources/12496#tree::archival_object_1273135

**Comment by laurensorensen** [comment]
Here is the argo link for H-2785, in case it's needed: https://argo.stanford.edu/view/druid:yt594yv4496

**Comment by laurensorensen** [comment]
Do we think that the data here is up to date, given the above?: https://github.com/sul-dlss/vt-arclight/tree/main/source_data/series 
I was going to us the series CSVs for this ticket: https://github.com/sul-dlss/vt-arclight/issues/433

**Comment by marlo-longley** [comment]
Hi @laurensorensen. Yes, if you added a new item to the collection (H-2785) we should add it to the item-level spreadsheet, and regenerate our data pipeline. Since you only made the addition in ASpace, if we were to regenerate that data from the spreadsheets, it would be erased.

Is the purpose of #433 preservation of our data spreadsheets? I'm not familiar with your aim there.

**Comment by laurensorensen** [comment]
Thanks for this! 
#433 is to add metadata to SDR on item-level. 
Ok, I will add to the item level spreadsheet. Confirming that these are the source spreadsheets you all start with re: the data pipeline: https://drive.google.com/drive/u/0/folders/1GD1Xfilwx9aJQvMMkZaSLXuwebWLuFlh

**Comment by thatbudakguy** [comment]
the canonical version of the source spreadsheet is https://github.com/sul-dlss/vt-arclight/blob/main/source_data/items_only.csv; the ones in google drive are just backups. if you've got Numbers or another non-excel editor you can use, feel free to edit that file and then we can get the changes pushed to github. happy to pair on doing this as well.
