### ISSUE TITLE
Create mailing list for maintainers

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#434]
Should include ATeam + Lauren, maybe Hannah.
Comment the list name here when done, and I will add to DevOpsDocs.
Ref #397

**Comment by laurensorensen** [comment]
Submitted request for a new list 
<img width="1003" alt="Screen Shot 2022-12-19 at 2 05 17 PM" src="https://user-images.githubusercontent.com/3269689/208534208-cae0815d-d18f-49b2-b332-e813ea01126f.png">

**Comment by laurensorensen** [comment]
Done. https://mailman.stanford.edu/mailman/admin/virtualtribunals-maintainers/general
