### ISSUE TITLE
Recaptcha error message visible

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#441]
This might be a known issue or something being worked on but just in case, there's a recaptcha error message showing at the bottom right of the viewport:

---

<img width="751" alt="Screen Shot 2023-01-05 at 3 26 32 PM" src="https://user-images.githubusercontent.com/101482/210892174-5b7cc20a-d5ea-4d61-9d3f-b2a597f13cf8.png">

**Comment by jcoyne** [comment]
@ggeisler it appears to work fine for me on stage and prod.  Where are you seeing the problem?
<img width="309" alt="Screenshot 2023-01-06 at 7 26 36 AM" src="https://user-images.githubusercontent.com/92044/211021597-c7bf0041-9bfc-4e6e-aa6c-f4c685e294bd.png">

**Comment by ggeisler** [comment]
@jcoyne I see it on both -stage-a and -prod, and I just double-checked that it wasn't a browser-specific thing; I see it on Firefox, Safari, and Chrome, on any page of the site.

**Comment by jcoyne** [comment]
@ggeisler are you going to specific nodes rather than the load balanced endpoint? (e.g. https://virtualtribunals-stage.stanford.edu/ or https://virtualtribunals.stanford.edu/)

**Comment by ggeisler** [comment]
Yep, that was it. It works fine if I go to the endpoints you listed. Will close this.

I guess I was using the specific nodes because they were posted somewhere in the past and my browser just keep offering those when I started typing the URL.
