### ISSUE TITLE
Omit separator after last attribute in results view attribute list

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#442]
Can we do something clever in the CSS (using `last-of-type` or something) to omit the separator dot after the last attribute in the list?

<img width="648" alt="Screen Shot 2023-01-05 at 3 35 35 PM" src="https://user-images.githubusercontent.com/101482/210893499-992d0381-a997-4652-94c5-6ebd632138d5.png">

**Comment by thatbudakguy** [comment]
I'll look into this.

**Comment by marlo-longley** [comment]
This only occurs when there is a fulltext match --- in this case, there actually is an item after the date.
We need to omit the bullet point in this case, but is functioning as expected
![Screen Shot 2023-01-05 at 18 06 01](https://user-images.githubusercontent.com/1328900/210897165-5d9d13cf-4e84-4810-b130-93a2ec31b52f.png)
