### ISSUE TITLE
Statements and Speeches series is missing from prod

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#449]
Statements and Speeches series is missing from ArcLight instance: https://docs.google.com/spreadsheets/d/12bvoR6tQZjYW3k_gLdrPseNgLR8ImpHf/edit?usp=share_link&ouid=116571178623773097335&rtpof=true&sd=true

**Comment by thatbudakguy** [comment]
It looks like the data for this series just never got uploaded to production ASpace somehow. I'm uploading it now, and will regenerate the EAD and reindex when it's done.

**Comment by marlo-longley** [comment]
@thatbudakguy can we do the reindexing in one go with #408 ? I am still working on unblocking that with #431, but once #431 and this issue are all set with the commits to the repo, we could just reindex once.

**Comment by marlo-longley** [comment]
Closed by #408
