### ISSUE TITLE
Remove parent container attribute in search result view for every level

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#462]
Unless I'm missing something, these links in search result items don't actually do anything other than refresh the current page:

<img width="735" alt="Screen Shot 2023-01-11 at 2 39 24 PM" src="https://user-images.githubusercontent.com/101482/211923555-284ce83e-58eb-4da4-89bb-8068642b22c1.png">

This isn't good because by offering the link we're basically telling the user there is something useful they'll see if they follow this link, but then we don't show them anything useful. So it's kind of false advertising and confusing.

If this is just a bug and we expect to produce something different (I'm not certain what the intention was, since it's different from the original design, now updated in #461), we should fix it.

If there's just a technical hurdle where we can't show a new page based on the parent item that is linked, we should just unlink the parent container label, leaving it displayed but unlinked.

Longer-term, my hope is this attribute actually goes away completely and is replaced by the attributes suggested in #461.

**Comment by marlo-longley** [comment]
Just some notes on a first pass over looking at this:

https://github.com/sul-dlss/vt-arclight/issues/161 is where the linking concept seemed to come from, and this is the PR https://github.com/sul-dlss/vt-arclight/pull/178

Here is where we attempt to render the link:
https://github.com/sul-dlss/vt-arclight/blob/a0d5afa114fd36e6af5d78d3f59d5c84d7f1b929/app/controllers/catalog_controller.rb#L159

We should probably try to debug that helper.

**Comment by marlo-longley** [comment]
don't show it at all actually -- after discussion with Gary.
