### ISSUE TITLE
Some search results do not display the "full document" link when results come back

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#487]
In the screenshot, I have searched "Goering" and a number of results came back. But the "31 Summaries" result doesn't have Goering in the title nor a link to the term in the document, as would be expected. 
<img width="1096" alt="Screen Shot 2023-01-19 at 11 21 55 AM" src="https://user-images.githubusercontent.com/3269689/213541796-15064efb-a139-4135-9262-3634ef6ca142.png">

**Comment by corylown** [comment]
@laurensorensen could you provide a URL with the search you conducted? I see completely different results when I search for `Goering`

**Comment by laurensorensen** [comment]
@corylown Yes, here you go: https://virtualtribunals-prod.stanford.edu/nuremberg?q=goering&search_field=all_fields&sort=title_sort+asc

**Comment by corylown** [comment]
This will require more investigation, but if I'm understanding how this works, in order for the full text results matches and link to show up in the results/index view we have to get a `highlighting` response from Solr. We get this response for `mt839rq8746aspace_909d5cb67683659311e54c91afb9afef` but not for `mt839rq8746aspace_860e7443d413ac80c161d10f97ab796d` even though there are matches for `Goering` in the `full_text_tesimv` field for document `mt839rq8746aspace_860e7443d413ac80c161d10f97ab796d`


`/solr/nta-arclight-prod/select?debugQuery=true&fq=id%3Amt839rq8746aspace_909d5cb67683659311e54c91afb9afef&hl.field=full_text_tesimv&hl=true&indent=true&q.op=OR&q=full_text_tesimv:goering`

```
  "highlighting":{
    "mt839rq8746aspace_909d5cb67683659311e54c91afb9afef":{
      "full_text_tesimv":[" objected to the admission in evidence of Exhibit GB ol ( TC—90) and Interrogation of <em>Goering</em> on the ground"]}},
```

vs.


`/solr/nta-arclight-prod/select?debugQuery=true&fq=id%3Amt839rq8746aspace_860e7443d413ac80c161d10f97ab796d&hl.field=full_text_tesimv&hl=true&indent=true&q.op=OR&q=full_text_tesimv:goering`

```
  "highlighting":{
    "mt839rq8746aspace_860e7443d413ac80c161d10f97ab796d":{}},
```

**Comment by laurensorensen** [comment]
Any updates on this? It seems to still be behaving this way when I click the search linked above.

**Comment by marlo-longley** [comment]
Hey @laurensorensen -- my understand of this ticket is that it will have to wait until a future workcycle as it was not release cirtical. Unfortunately I don't have any progress update for ya!

**Comment by corylown** [comment]
My best guess is we're running into Solr's default limit on `hl.maxAnalyzedChars` which will not highlight beyond the first 51200 characters. See https://solr.apache.org/guide/solr/latest/query-guide/highlighting.html#common-highlighter-parameters

**Comment by corylown** [comment]
@laurensorensen this is fixed now in production: https://virtualtribunals-prod.stanford.edu/nuremberg?q=goering&search_field=all_fields&sort=title_sort+asc
