### ISSUE TITLE
Explain what EAD means in the "Download EAD" section

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#491]
This was raised in the stakeholder demo yesterday. Not sure what the design or conclusions should be, or if we should implement this at all. @laurensorensen @ggeisler

**Comment by laurensorensen** [comment]
I do not think it's necessary to do this before the release. I'm open to discussing how we do this and getting feedback from the AL community if @ggeisler seems like that's a good idea.. I kind of think this might be something that would be an Arclight core feature rather than custom? And we might want to ask at another round of user interviews?

**Comment by ggeisler** [comment]
I don't think this has enough potential to confuse users that it deserves the awkward workaround it will likely require.

If a user doesn't know what "EAD" means, are they likely to be bothered by a button that is fairly out of the way and doesn't impact their normal use of the site? The button is intended for users who **do** know what "EAD" means and might want to download a copy. If there was as straightforward way to educate users who don't know what it means, sure, that would be nice, just to inform EAD-unaware users this is likely not something they care about. But an obvious solution that doesn't negatively affect the UI isn't clear to me.

Potentially we could add an info icon (the "i" icon we use for the More info button) and use that to display some explanation. But we also have to keep in mind that this is not a dedicated EAD download button. It currently is in VT, but the button is set up (unless something has changed) to handle multiple types of downloads (EAD, PDF of the finding aid, etc.) when they exist. In that case the button label is just "Download" with a dropdown affordance to show the download options. So the info icon doesn't work so well as a general solution. We'd have to make the button customized for VT.

I could work on this more if necessary, it just doesn't seem important enough to me, at least until we get some sort of feedback leading us to think it's something that will address a real issue.

**Comment by marlo-longley** [comment]
@laurensorensen @ggeisler seems like from the demo today, this is actually something we need to do. Thoughts?

**Comment by ggeisler** [comment]
Here's a suggested design. Add a new icon to the "Download EAD" button:

<img width="381" alt="Screen Shot 2023-01-27 at 1 44 18 PM" src="https://user-images.githubusercontent.com/101482/215224218-13a4334e-f83c-4308-aaf3-5a6d148e4faa.png">

---

On user selection/mouseover, display a tooltip with an explanation of EAD:

<img width="381" alt="Screen Shot 2023-01-27 at 4 16 59 PM" src="https://user-images.githubusercontent.com/101482/215224307-2b8e3b9e-3350-45bc-94cb-768b73e180ac.png">

---

This involves:

- Add a [question mark icon](https://icons.getbootstrap.com/icons/question-circle-fill/) after the "Download EAD" button label. It should be sized and styled identically to the information icon used in the adjacent More info button.
- Ensure there is `0.25rem` horizontal margin between the button label and the new icon.
- Attach a [Bootstrap tooltip](https://getbootstrap.com/docs/5.2/components/tooltips/) to the new icon. Use the "Tooltip on bottom" placement option. Use the default styling (white text on black background).
- Use the text `EAD is an abbreviation for “Encoded Archival Description,” an XML standard for encoding archival finding aids. The downloadable EAD file contains the entire IMT content inventory in XML format.` for the tooltip text. (If anyone has ideas for a better definition, while not requiring much more space than this suggestion, feel free to edit.)

You could make the tooltip body somewhat wider than in my mockup, to reduce the vertical space it requires. But I think the max width shouldn't exceed the outer edges of the Download EAD and More info buttons above it.
