### ISSUE TITLE
Remove virtualtribunals.stanford.edu from behind VPN

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#492]
I don't know who controls this, what the process to request it is, or whether our dependent servers (redis, e.g.) need to also be considered. We need to understand the process and the timing for doing this.

**Comment by laurensorensen** [comment]
Yesterday at the PR meeting, Tom mentioned enabling Basic Auth so that there could be a log-in for the other stakeholders but not have the site be totally open on the web until the press release goes out
