### ISSUE TITLE
Do we want the reCAPTCHA badge to appear on the virtual tribunals site?

### ISSUE THREAD

**Issue by corylown** [sul-dlss/vt-arclight#493]
Currently every page of the virtual tribunals site displays the reCAPTCHA badge in the lower right corner.

<img width="384" alt="Screen Shot 2023-01-20 at 1 38 32 PM" src="https://user-images.githubusercontent.com/458247/213779733-564a6c49-77fd-4869-979e-d2bd1f89f7aa.png">

If we'd prefer not have this badge display we can hide it, but we'd be obligated to add some messaging to the feedback form acknowledging that we're using reCAPTCHA. See the Google FAQ on this: https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed

**Comment by ggeisler** [comment]
I'd definitely vote for hiding the badge and adding the required text to the feedback form. That way it is only intrusive to the relatively small subset of users who choose to open the feedback form.

It could look like:

<img width="1177" alt="Screen Shot 2023-01-20 at 11 56 11 AM" src="https://user-images.githubusercontent.com/101482/213782789-85dac4d7-3ab9-460c-b554-2f2a940f268c.png">

---

by adding this code:

```
<p class="text-secondary mt-2 mb-0">This site is protected by reCAPTCHA and the Google
    <a href="https://policies.google.com/privacy">Privacy Policy</a> and
  <a href="https://policies.google.com/terms">Terms of Service</a> apply.</p>
```

directly after the `<input class="form-control" required="required" type="email" name="email" id="email">` part of the form.

**Comment by laurensorensen** [comment]
Agree with @ggeisler.
