### ISSUE TITLE
DashLane password manager add-on displays widgets for hidden feedback form inputs

### ISSUE THREAD

**Issue by corylown** [sul-dlss/vt-arclight#495]
This is a question for @laurensorensen -- do we want to try to address this? I think this is a flaw with the Dashlane add-on and would only impact dashlane users, but they suggest adding attributes to the form fields to prevent the password manager from trying to interact with forms that are not for login: https://support.dashlane.com/hc/en-us/articles/4420122792594-Optimize-your-web-forms-for-Dashlane-Autofill

From the docs linked above, adding a `data-form-type="other"` attribute to the input field prevents the add-on from trying to interact with the form.

![PastedGraphic-1-1 copy](https://user-images.githubusercontent.com/458247/213781030-47bdf081-33b5-4cb3-a0a3-c95fa2c9a542.jpg)

**Comment by laurensorensen** [comment]
Yes it would be good to do this fix if possible. If it's a ton of work, we could provide Tom with a work-around (uninstall the extension temporarily? Use Safari or another browser sans extension?). He's going to be presenting to other stakeholders, so will have to find some kind of fix.

**Comment by marlo-longley** [comment]
@corylown I'm willing to go in and add this `data-form-type="other"` to forms, but the area in the screenshot shown by @laurensorensen is not a form. It's simply a `p` tag. I'll dig in to this a bit more.

**Comment by corylown** [comment]
@marlo-longley I think dashlane is detecting the fields on the hidden feedback form
