### ISSUE TITLE
Unable to send form feedback once in VT Arclight (not landing page)

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#497]
I tested the contact form after Hannah said there were some issues yesterday. It is working to send a message thru the landing page, but when I click through to VT/Arclight Taube site I get the message in the screenshot (it weirdly re-directs to the landing page after hitting "send message" in feedback form.)
<img width="579" alt="Screen Shot 2023-01-20 at 12 00 16 PM" src="https://user-images.githubusercontent.com/3269689/213794969-334d8b67-75f2-40db-b324-d04a1f0f0299.png">

**Comment by laurensorensen** [comment]
Specifically I sent the form from virtualtribunals.stanford.edu/nuremberg that returned the error.

**Comment by corylown** [comment]
I'm wondering if something is wrong with the recaptcha setup. I'm seeing this message on the Google admin page:

>  We detected that your site is not verifying reCAPTCHA tokens. Please see [our developer site](https://developers.google.com/recaptcha/docs/verify#api-request) for more information.
