### ISSUE TITLE
Add a way for stakeholders (funders, etc) outside of Stanford to access site pre-release

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#500]
Yesterday at the meeting with Gabrielle, Tom asked to have the NTA site have Basic Auth enabled before the site goes live to the public so that the funder can log-in and look around. He was specific that it shouldn't require VPN but also not be open to the public yet. Let me know if you need any more details from me to make this happen.

**Comment by marlo-longley** [comment]
This is related to #492

**Comment by laurensorensen** [comment]
This is no longer needed per email from Tom 1/26
