### ISSUE TITLE
Data error where new item in collection displays as "Linear Feet" rather than item

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#512]
Linear feet shouldn't be displayed here or be in the data at all. First screenshot is what appears in search results and second is in the metadata on the item level page. It should be item(s) instead like the rest. 
<img width="1368" alt="Screen Shot 2023-01-26 at 3 32 36 PM" src="https://user-images.githubusercontent.com/3269689/214974079-2946c90f-bc4a-4822-8e86-04f37a5c2439.png">

<img width="1368" alt="Screen Shot 2023-01-26 at 3 32 36 PM" src="https://user-images.githubusercontent.com/3269689/214974135-d43962e2-9001-44b7-9f07-3942ec2baa2b.png">

**Comment by cbeer** [comment]
I'm seeing "1 Linear Feet" in the exported EAD:

```
<extent altrender="materialtype spaceoccupied">1 Linear Feet</extent>
```

Is it possible to remove it from the EAD, or are you asking us to suppress that information in VT?

**Comment by laurensorensen** [comment]
@cbeer Ok thanks, I'll take it out of the EAD. I guess it must have been a typo or something. I'll post back here when it's ready in stage and prod

**Comment by laurensorensen** [comment]
Ok, the data has been fixed in both stage and prod.
