### ISSUE TITLE
Investigate how to relate in ASpace video transcripts to main druid

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#61]
There will eventually be 3-4 transcripts accessioned that will be related to each of the 37 video "main" druids. Not sure how this relationship will be expressed in EAD. Investigate if DACS has guidance or if there's any info in the EAD2002 schema.

**Comment by marlo-longley** [comment]
Thanks @laurensorensen. We should get an example of a video into the EAD as soon as we can, and try this out. Do these transcripts each have their own druids?

I am happy to pair to investigate.

**Comment by marlo-longley** [comment]
@laurensorensen can we close this now that we spoke to Geoff and saw an example of the media player?
FYI I created #139 to track that specific question.
