### ISSUE TITLE
Do the two different EAD hierarchies display differently in ArcLight? 

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/vt-arclight#63]
For a few Series groupings, there is a Series > Sub-series > File > Item hierchay, while there is: 
Series > Sub-series > File grouping for the res of the Series. 

Currently there is only a Series > Sub-series > File example up in ArcLight. 

This week, @laurensorensen will upload a fixture (sample data) for the Series > Sub-series > File > Item hierarchy and make sure with the team that it works / displays as expected in ArcLight from ASpace.

**Comment by laurensorensen** [comment]
Another concern is if the Digital Object will display as "File" and "Item" if in one series "File" is the bottom most in one Series hierarchy and "Item" is the bottom most in another Series hierarchy.

**Comment by marlo-longley** [comment]
Thanks for writing this up @laurensorensen -- I know you're working on the Exhibits series, and we have Document Books. Between these two series, will we get a sampling of both types of hierarchy?

**Comment by laurensorensen** [comment]
@marlo-longley I'm working on all of them now, so there will be an example of sample data for all Series groupings and so all hierarchies.

**Comment by laurensorensen** [comment]
I had to make a small change to the data model. Turns out the court transcripts are not consistently one-day only, so I am formatting them as Month only, not by day. This will be reflected in the sample data and I've edited the visual model here: https://docs.google.com/spreadsheets/d/1Xz0hq28tyhESPTAcpowhlhw8JHNUManDWjP3hXZDkPg/edit#gid=1453131742

**Comment by laurensorensen** [comment]
Ok, I made sample data happen for all the series here: 
http://spec-as-stage.stanford.edu:8080/resources/10208/edit#tree::resource_10208

There was one error I couldn't figure out, below. I'm also trying to make sure all the dates are formatted ok and all that. Will probably take Mon/Tues to do this. 

`Row 37
Unable to create agent link: '1' is not a valid role
Unable to create agent link: '1' is not a valid role
Unable to create agent link: '1' is not a valid role
Unable to create agent link: '1' is not a valid role
Unable to create agent link: '1' is not a valid role
Unable to create agent link: '1' is not a valid role
Unable to create agent link: '1' is not a valid role
Digital Object created: 'Official Commission Transcript, Albert KESSELRING, 3 July 1946' /repositories/2/digital_objects/56067 [05980218d91113954a99fd72ffc214ead]
Archival Object created: 'Official Commission Transcript, Albert KESSELRING, 3 July 1946' (/repositories/2/archival_objects/1164672) [05980218d91113954a99fd72ffc214ea]`

**Comment by laurensorensen** [comment]
I'm able to find that all fields mapped over from the original data except for:
- Language fields
- Box information (e.g. Box 11)

Wondering if you can see this info on the ArcLight side of things @marlo-longley ?

**Comment by marlo-longley** [comment]
@laurensorensen could you let me know the titles of two series, one that represents the  Series > Sub-series > File > Item hierarchy, and the other with Series > Sub-series > File ?

**Comment by marlo-longley** [comment]
Update: these hierarchies display the same, correctly.
