### ISSUE TITLE
Update layout and styling to match SUL theme

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vt-arclight#65]
The visual design goal for the NTA site is to follow the general SUL application look and feel. Below are the most fundamental tasks I can think of to update the basic Blacklight/ArcLight layout and styling to reflect a SUL-branded layout and styling.

In general, I'd recommend using [Exhibits](https://github.com/sul-dlss/exhibits) as a model, although for the topbar and footer, most public-facing SUL applications should be close to what we want for NTA.

<img width="1010" alt="Screen Shot 2022-10-24 at 2 07 40 PM" src="https://user-images.githubusercontent.com/101482/197632300-525f98a5-c7cf-4adb-8d54-b99eda3eff8b.png">

- **A:** #66 
- **B: Customize the site header/masthead**: Detailed ticket TBD. This might be the most customized element and I need to think about how to make it as visually interesting as possible. For now, using `#f2f1eb` for the background color is probably sufficient.
- **C: Update content and component styling**: Detailed ticket TBD to recommend details for customizing the typography and colors to match SUL styles. Some of the details (link colors, facet element colors, font-sizing) vary among our public-facing apps, but I'd suggest that Exhibits might be the most appropriate model for these in NTA.
- **D:**  #67

**Comment by marlo-longley** [comment]
Closing; Part C will be addressed in smaller tickets and PRs.
